import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, CircleX, Globe2, Loader2, Mail, Signpost } from 'lucide-react';
import { loadLesenArchive, type LesenArchiveData, type LesenArchiveOption, type LesenArchiveTeil1Task, type LesenArchiveTeil2Task, type LesenArchiveTeil3Task } from '@/data/lesen/archiveData';
import { CompactTranslationEye } from '@/components/common/CompactTranslationEye';
import { HoverTranslateText } from '@/components/common/HoverTranslateText';
import { GuidedTaskPrep } from '@/components/GuidedTaskPrep';
import { cn } from '@/lib/utils';

interface Props { onBack:()=>void; onComplete:(score:number,total:number)=>void }
type Part=1|2|3; type Bin='richtig'|'falsch'; type Choice='a'|'b';
type PartProgress={nextIndex:number;completedTasks:number;answered:number;correct:number;mistakes:string[];credited:string[]};
type LesenProgress=Record<'1'|'2'|'3',PartProgress>;
const STORAGE_KEY='otto-a1-lesen-progress-v2';
const EMPTY_PART:PartProgress={nextIndex:0,completedTasks:0,answered:0,correct:0,mistakes:[],credited:[]};
const INTRO_DE='Lesen hat drei Teile. Sie lesen kurze E-Mails und Nachrichten, Webseiten und Anzeigen sowie Schilder und Hinweise. Finden Sie die wichtige Information und wählen Sie die passende Antwort.';
const INTRO_RU='Чтение состоит из трёх частей: короткие письма и сообщения, сайты и объявления, вывески и указания. Нужно найти важную информацию и выбрать подходящий ответ.';
const META={1:{title:'Briefe & Nachrichten',de:'Kurze E-Mails und Nachrichten lesen und Aussagen als richtig oder falsch markieren.',ru:'Короткие письма и сообщения: прочитать и определить, верно или неверно утверждение.',icon:Mail},2:{title:'Webseiten & Anzeigen',de:'Eine Situation lesen und zwischen zwei Informationsquellen a oder b wählen.',ru:'Прочитать ситуацию и выбрать, где есть нужная информация: a или b.',icon:Globe2},3:{title:'Schilder & Hinweise',de:'Kurze Hinweise, Schilder und Anzeigen lesen und Aussagen prüfen.',ru:'Прочитать вывески и объявления и проверить утверждение.',icon:Signpost}} as const;

function readProgress():LesenProgress{
  const blank=():PartProgress=>({...EMPTY_PART,mistakes:[],credited:[]});
  try{
    const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}') as Partial<LesenProgress>;
    const safe=(p?:Partial<PartProgress>):PartProgress=>({nextIndex:Math.max(0,Math.min(49,Number(p?.nextIndex)||0)),completedTasks:Math.max(0,Number(p?.completedTasks)||0),answered:Math.max(0,Number(p?.answered)||0),correct:Math.max(0,Number(p?.correct)||0),mistakes:Array.isArray(p?.mistakes)?p!.mistakes!.map(String).slice(-120):[],credited:Array.isArray(p?.credited)?p!.credited!.map(String).slice(-200):[]});
    return {'1':safe(raw['1']),'2':safe(raw['2']),'3':safe(raw['3'])};
  }catch{return {'1':blank(),'2':blank(),'3':blank()}}
}
function saveProgress(value:LesenProgress){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(value))}catch{/* ignore */}}
function partKey(part:Part){return String(part) as '1'|'2'|'3'}

export function ReadingModule({onBack,onComplete}:Props){
 const[data,setData]=useState<LesenArchiveData|null>(null),[error,setError]=useState<string|null>(null),[part,setPart]=useState<Part|null>(null),[index,setIndex]=useState(0),[checked,setChecked]=useState(false),[finished,setFinished]=useState(false),[bin,setBin]=useState<Bin|null>(null),[choice,setChoice]=useState<Choice|null>(null),[multi,setMulti]=useState<(Bin|null)[]>([]),[progress,setProgress]=useState<LesenProgress>(readProgress),[lastAdd,setLastAdd]=useState(0);
 useEffect(()=>{let live=true;loadLesenArchive().then(v=>live&&setData(v)).catch((e:unknown)=>live&&setError(e instanceof Error?e.message:'Не удалось загрузить задания Lesen.'));return()=>{live=false}},[]);
 useEffect(()=>saveProgress(progress),[progress]);
 const tasks=!data||!part?[]:part===1?data.teil1:part===2?data.teil2:data.teil3,current=tasks[index];
 const currentProgress=part?progress[partKey(part)]:EMPTY_PART;
 const total=part===1?150:50;
 const clear=()=>{setChecked(false);setBin(null);setChoice(null);setMulti([]);setLastAdd(0)};
 const reset=()=>{if(!part)return;setIndex(0);setFinished(false);clear();window.scrollTo({top:0,behavior:'smooth'})};
 const open=(p:Part)=>{const saved=progress[partKey(p)];setPart(p);setIndex(saved.completedTasks>=50?49:saved.nextIndex);setFinished(saved.completedTasks>=50);clear();window.scrollTo({top:0,behavior:'smooth'})};
 const back=()=>{setPart(null);setFinished(false);clear();window.scrollTo({top:0,behavior:'smooth'})};
 const canCheck=()=>{if(!part||!current||checked)return false;if(part===1){const t=current as LesenArchiveTeil1Task;return multi.length===t.statements.length&&multi.every(Boolean)}return part===2?choice!==null:bin!==null};
 const check=()=>{
  if(!canCheck()||!part||!current)return;
  let add=0,answeredNow=1;const mistakes:string[]=[];
  if(part===1){const t=current as LesenArchiveTeil1Task;answeredNow=t.statements.length;add=t.statements.reduce((n,s,i)=>{const expected:Bin=s.correct?'richtig':'falsch';const ok=multi[i]===expected;if(!ok)mistakes.push(`Teil 1 · Aufgabe ${index+1}.${i+1}: ${s.statement}`);return n+(ok?1:0)},0)}
  else if(part===2){const t=current as LesenArchiveTeil2Task;add=choice===t.correct?1:0;if(!add)mistakes.push(`Teil 2 · Aufgabe ${index+1}: ${t.situation}`)}
  else{const t=current as LesenArchiveTeil3Task;const expected:Bin=t.correct==='Richtig'?'richtig':'falsch';add=bin===expected?1:0;if(!add)mistakes.push(`Teil 3 · Aufgabe ${index+1}: ${t.statement}`)}
  setLastAdd(add);setChecked(true);
  const key=`${part}-${index}`;const pk=partKey(part);const already=progress[pk].credited.includes(key);
  if(!already){
    const nextPart:PartProgress={...progress[pk],nextIndex:Math.min(49,index+1),completedTasks:Math.min(50,progress[pk].completedTasks+1),answered:progress[pk].answered+answeredNow,correct:progress[pk].correct+add,mistakes:[...progress[pk].mistakes,...mistakes].slice(-120),credited:[...progress[pk].credited,key].slice(-200)};
    setProgress(prev=>({...prev,[pk]:nextPart}));
    onComplete(add,answeredNow);
  }
 };
 const next=()=>{if(!checked||!part)return;const done=progress[partKey(part)].completedTasks>=50||index===49;if(done){setFinished(true);window.scrollTo({top:0,behavior:'smooth'});return}setIndex(v=>Math.min(49,v+1));clear();window.scrollTo({top:0,behavior:'smooth'})};
 if(error)return <div className="animate-fade-in pb-8"><Back onClick={onBack}/><div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-900"><b>Не удалось открыть Lesen</b><p className="mt-1 text-sm">{error}</p></div></div>;
 if(!data)return <div className="flex min-h-[260px] items-center justify-center text-center text-slate-500"><div><Loader2 className="mx-auto h-7 w-7 animate-spin"/><p className="mt-3 text-sm font-semibold">Загружаю задания Lesen…</p></div></div>;
 if(!part)return <Home onBack={onBack} onOpen={open} progress={progress}/>;
 if(finished)return <Result part={part} score={currentProgress.correct} total={total} completed={currentProgress.completedTasks} onRetry={reset} onBack={back}/>;
 if(!current)return <div><Back onClick={back}/><p className="mt-4">В этой части нет задания.</p></div>;
 const prepFocus=part===1?(current as LesenArchiveTeil1Task).statements[0]?.statement||instruction(part):part===2?(current as LesenArchiveTeil2Task).situation:(current as LesenArchiveTeil3Task).statement;
 const prepTip=part===1?'Сначала поймите смысл утверждения, потом ищите в тексте подтверждение или противоречие.':part===2?'Определите, какая именно информация нужна в ситуации, и только потом сравнивайте варианты A и B.':'Сначала найдите запрет, разрешение, время или условие на табличке — это обычно ключ к ответу.';
 return <div className="animate-fade-in pb-8"><div className="mb-4 flex items-start gap-3"><Back onClick={back}/><div className="min-w-0 flex-1"><h1 className="text-xl font-black text-slate-950">Lesen · Teil {part}</h1><p className="mt-1 text-sm text-slate-500">Aufgabe {index+1} von 50 · выполнено {currentProgress.completedTasks}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-teal-600" style={{width:`${(currentProgress.completedTasks/50)*100}%`}}/></div></div><CompactTranslationEye parts={[`Lesen Teil ${part}`,META[part].de]} translations={[`Чтение · часть ${part}`,META[part].ru]} title="Перевод"/></div>
 <div className="mb-4 flex items-start justify-between gap-3 rounded-xl border-l-4 border-teal-600 bg-teal-50 px-4 py-3 text-sm leading-6 text-slate-700"><HoverTranslateText text={instruction(part)}/><CompactTranslationEye parts={[instruction(part)]} title="Перевод задания"/></div>
 <GuidedTaskPrep focus={prepFocus} tip={prepTip}/>
 {part===1&&<Teil1 task={current as LesenArchiveTeil1Task} answers={multi} checked={checked} onAnswer={(i,a)=>{if(checked)return;const len=(current as LesenArchiveTeil1Task).statements.length;setMulti(prev=>{const v=Array<Bin|null>(len).fill(null);prev.forEach((x,j)=>{if(j<len)v[j]=x});v[i]=a;return v})}}/>}
 {part===2&&<Teil2 task={current as LesenArchiveTeil2Task} selected={choice} checked={checked} onSelect={a=>!checked&&setChoice(a)}/>} 
 {part===3&&<Teil3 task={current as LesenArchiveTeil3Task} selected={bin} checked={checked} onSelect={a=>!checked&&setBin(a)}/>} 
 {checked&&part!==1&&<SingleFeedback part={part} task={current as LesenArchiveTeil2Task|LesenArchiveTeil3Task} choice={choice} bin={bin}/>} 
 {checked&&<p className="mb-4 text-sm font-semibold text-slate-500">За это задание: {lastAdd}/{part===1?(current as LesenArchiveTeil1Task).statements.length:1}</p>}
 <div className="flex justify-end">{!checked?<button onClick={check} disabled={!canCheck()} className="min-h-12 rounded-xl bg-slate-900 px-6 py-3 font-bold text-white disabled:opacity-40">Проверить</button>:<button onClick={next} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-slate-900 px-6 py-3 font-bold text-white">{index===49?'Результат':'Следующее задание'}<ArrowRight className="h-4 w-4"/></button>}</div></div>;
}

function Home({onBack,onOpen,progress}:{onBack:()=>void;onOpen:(p:Part)=>void;progress:LesenProgress}){return <div className="animate-fade-in pb-8"><div className="mb-5 flex items-start gap-3"><Back onClick={onBack}/><div className="min-w-0 flex-1"><h1 className="text-3xl font-black text-slate-950">Lesen</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600"><HoverTranslateText text={INTRO_DE}/></p></div><CompactTranslationEye parts={[INTRO_DE]} translations={[INTRO_RU]} title="Перевод Lesen"/></div><div className="grid gap-4 lg:grid-cols-3">{([1,2,3] as Part[]).map(p=>{const m=META[p],Icon=m.icon,s=progress[partKey(p)];return <div key={p} className="flex min-h-[300px] flex-col rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-start justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-900 text-white"><Icon className="h-6 w-6"/></span><CompactTranslationEye parts={[`Teil ${p}: ${m.title}`,m.de]} translations={[`Часть ${p}`,m.ru]} title={`Перевод Teil ${p}`}/></div><span className="text-xs font-black uppercase tracking-wider text-teal-700">Teil {p}</span><h2 className="mt-1 text-xl font-black"><HoverTranslateText text={m.title}/></h2><p className="mt-3 text-sm leading-6 text-slate-600"><HoverTranslateText text={m.de}/></p><div className="mt-auto pt-5"><p className="mb-2 text-sm font-bold text-teal-900">50 оригинальных заданий от Отто</p>{s.completedTasks>0&&<p className="mb-3 text-xs text-slate-500">Выполнено: {s.completedTasks}/50 · правильно: {s.correct}/{s.answered}</p>}<button onClick={()=>onOpen(p)} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 font-bold text-white">{s.completedTasks>0&&s.completedTasks<50?'Продолжить':'Начать тренировку'}<ArrowRight className="h-4 w-4"/></button></div></div>})}</div></div>}

function Teil1({task,answers,checked,onAnswer}:{task:LesenArchiveTeil1Task;answers:(Bin|null)[];checked:boolean;onAnswer:(i:number,a:Bin)=>void}){return <section className="mb-4 rounded-2xl border bg-[#fffefa] p-4 shadow-sm sm:p-5"><p className="mb-2 text-xs font-bold uppercase text-slate-400">{task.format}</p><div className="whitespace-pre-line rounded-xl bg-white p-4 text-[15px] leading-7"><HoverTranslateText text={task.text}/></div><div className="mt-4 space-y-3">{task.statements.map((s,i)=>{const selected=answers[i]??null,expected:Bin=s.correct?'richtig':'falsch',ok=checked&&selected===expected;return <div key={i} className="rounded-xl border bg-white p-4"><p className="text-[15px] font-semibold leading-6">{i+1}. <HoverTranslateText text={s.statement}/></p><div className="mt-3 grid grid-cols-2 gap-2"><AB label="Richtig" value="richtig" selected={selected} disabled={checked} checked={checked} correctValue={expected} onSelect={v=>onAnswer(i,v as Bin)}/><AB label="Falsch" value="falsch" selected={selected} disabled={checked} checked={checked} correctValue={expected} onSelect={v=>onAnswer(i,v as Bin)}/></div>{checked&&<div className={cn('mt-3 rounded-lg px-3 py-2 text-sm',ok?'bg-emerald-50 text-emerald-900':'bg-rose-50 text-rose-900')}><div className="flex gap-2">{ok?<CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0"/>:<CircleX className="mt-0.5 h-4 w-4 shrink-0"/>}<div><b>{ok?'Правильно':`Правильный ответ: ${expected==='richtig'?'Richtig':'Falsch'}`}</b>{!ok&&s.explanation&&<BilingualWhy text={s.explanation}/>}</div></div></div>}</div>})}</div></section>}

function Teil2({task,selected,checked,onSelect}:{task:LesenArchiveTeil2Task;selected:Choice|null;checked:boolean;onSelect:(a:Choice)=>void}){return <section className="mb-4 space-y-3"><div className="rounded-2xl border bg-white p-4 text-[16px] font-semibold leading-7"><HoverTranslateText text={task.situation}/></div><div className="grid min-w-0 gap-3 sm:grid-cols-2"><OptionCard label="A" option={task.a} format={task.format} selected={selected==='a'} checked={checked} correct={task.correct==='a'} onClick={()=>onSelect('a')}/><OptionCard label="B" option={task.b} format={task.format} selected={selected==='b'} checked={checked} correct={task.correct==='b'} onClick={()=>onSelect('b')}/></div></section>}
function OptionCard({label,option,format,selected,checked,correct,onClick}:{label:'A'|'B';option:LesenArchiveOption;format:LesenArchiveTeil2Task['format'];selected:boolean;checked:boolean;correct:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} disabled={checked} className={cn('min-w-0 rounded-2xl border-2 p-4 text-left transition',checked&&selected?(correct?'border-emerald-500 bg-emerald-50':'border-rose-500 bg-rose-50'):selected?'border-blue-300 bg-blue-50':'border-slate-200 bg-white')}><div className="mb-3 flex items-center justify-between"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900 text-sm font-black text-white">{label}</span>{checked&&selected&&correct&&<CheckCircle2 className="h-5 w-5 text-emerald-700"/>}{checked&&selected&&!correct&&<CircleX className="h-5 w-5 text-rose-700"/>}</div><OptionContent option={option} format={format}/></button>}
function OptionContent({option,format}:{option:LesenArchiveOption;format:LesenArchiveTeil2Task['format']}){if(format==='table'&&option.rows)return <div className="max-w-full overflow-x-auto"><table className="min-w-[520px] border-collapse text-xs"><tbody>{option.rows.map((r,i)=><tr key={i} className="border-b last:border-b-0">{r.map((c,j)=><td key={j} className="whitespace-nowrap px-2 py-2 first:pl-0"><HoverTranslateText text={c||'—'}/></td>)}</tr>)}</tbody></table></div>;return <div className="min-w-0">{option.url&&<p className="break-all text-xs font-semibold text-teal-700">{option.url}</p>}{option.title&&<h3 className="mt-1 text-base font-black"><HoverTranslateText text={option.title}/></h3>}{option.lines&&<div className="mt-2 space-y-1 text-sm leading-5 text-slate-700">{option.lines.map((x,i)=><p key={i}><HoverTranslateText text={x}/></p>)}</div>}</div>}

function Teil3({task,selected,checked,onSelect}:{task:LesenArchiveTeil3Task;selected:Bin|null;checked:boolean;onSelect:(a:Bin)=>void}){const expected:Bin=task.correct==='Richtig'?'richtig':'falsch';return <section className="mb-4 rounded-2xl border bg-white p-4 shadow-sm sm:p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400"><HoverTranslateText text={task.place}/></p>{task.heading&&<h2 className="mt-2 text-xl font-black"><HoverTranslateText text={task.heading}/></h2>}<div className="mt-3 rounded-xl bg-slate-50 p-4 text-sm leading-6">{task.text.map((x,i)=><p key={i}><HoverTranslateText text={x}/></p>)}</div><div className="mt-4 border-t pt-4 text-[16px] font-semibold leading-7"><HoverTranslateText text={task.statement}/></div><div className="mt-4 grid grid-cols-2 gap-3"><AB label="Richtig" value="richtig" selected={selected} disabled={checked} checked={checked} correctValue={expected} onSelect={v=>onSelect(v as Bin)}/><AB label="Falsch" value="falsch" selected={selected} disabled={checked} checked={checked} correctValue={expected} onSelect={v=>onSelect(v as Bin)}/></div></section>}
function AB({label,value,selected,disabled,checked,correctValue,onSelect}:{label:string;value:string;selected:string|null;disabled:boolean;checked:boolean;correctValue:string;onSelect:(v:string)=>void}){return <button type="button" disabled={disabled} onClick={()=>onSelect(value)} className={cn('min-h-12 rounded-xl border-2 px-3 py-2.5 font-bold transition',checked&&selected===value?(value===correctValue?'border-emerald-500 bg-emerald-50 text-emerald-900':'border-rose-500 bg-rose-50 text-rose-900'):selected===value?'border-blue-300 bg-blue-50 text-slate-900':'border-slate-200 bg-white text-slate-900')}>{label}</button>}
function SingleFeedback({part,task,choice,bin}:{part:Part;task:LesenArchiveTeil2Task|LesenArchiveTeil3Task;choice:Choice|null;bin:Bin|null}){if(part===2){const t=task as LesenArchiveTeil2Task;return <Feedback correct={choice===t.correct} label={t.correct.toUpperCase()} why={t.why}/>};const t=task as LesenArchiveTeil3Task,expected:Bin=t.correct==='Richtig'?'richtig':'falsch';return <Feedback correct={bin===expected} label={t.correct} why={t.why}/>}
function Feedback({correct,label,why}:{correct:boolean;label:string;why:string}){return <div className={cn('mb-4 rounded-2xl border p-4',correct?'border-emerald-200 bg-emerald-50':'border-rose-200 bg-rose-50')}><div className="flex gap-3">{correct?<CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-700"/>:<CircleX className="h-5 w-5 shrink-0 text-rose-700"/>}<div><b>{correct?'Правильно':`Неверно. Правильный ответ: ${label}`}</b>{!correct&&why&&<BilingualWhy text={why}/>}</div></div></div>}
function BilingualWhy({text}:{text:string}){const[pair,setPair]=useState<{de:string;ru:string}|null>(null);useEffect(()=>{const controller=new AbortController();setPair(null);fetch('/api/translate-task',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'explain-pair',text}),signal:controller.signal}).then(r=>r.json()).then(p=>{if(!controller.signal.aborted&&p?.de&&p?.ru)setPair({de:String(p.de),ru:String(p.ru)})}).catch(()=>{});return()=>controller.abort()},[text]);return <div className="mt-2 space-y-1 text-sm leading-6 text-slate-700">{pair?<><p><b>Deutsch:</b> {pair.de}</p><p><b>Русский:</b> {pair.ru}</p></>:<p>{text}</p>}</div>}
function Result({part,score,total,completed,onRetry,onBack}:{part:Part;score:number;total:number;completed:number;onRetry:()=>void;onBack:()=>void}){return <div className="animate-fade-in"><div className="rounded-3xl border bg-white p-7 text-center shadow-sm"><BookOpen className="mx-auto h-12 w-12 text-teal-700"/><h1 className="mt-4 text-2xl font-black">Lesen · Teil {part}</h1><p className="mt-3 text-5xl font-black">{score}/{total}</p><p className="mt-2 text-sm text-slate-500">Выполнено заданий: {completed}/50</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={onRetry} className="min-h-11 rounded-xl border px-5 font-bold">Просмотреть с начала</button><button onClick={onBack} className="min-h-11 rounded-xl bg-slate-900 px-5 font-bold text-white">К частям Lesen</button></div></div></div>}
function Back({onClick}:{onClick:()=>void}){return <button onClick={onClick} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border bg-white" aria-label="Назад"><ArrowLeft className="h-5 w-5"/></button>}
function instruction(part:Part){return part===1?'Lesen Sie den Text und die drei Aussagen. Wählen Sie bei jeder Aussage: Richtig oder Falsch.':part===2?'Lesen Sie die Situation. Wo finden Sie die passende Information? Wählen Sie a oder b.':'Lesen Sie den Hinweis und die Aussage. Wählen Sie: Richtig oder Falsch.'}
