import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Eye, Lightbulb, RefreshCw } from 'lucide-react';
import { speakingTeil1, speakingTeil2Cards, speakingTeil3Cards, type SpeakingPart } from '@/data/speaking';
import { freeSpeakingTopics } from '@/data/speakingFree';
import { SpeakingCardIllustration } from '@/components/sprechen/SpeakingCardIllustration';
import { VoiceRecorder } from '@/components/sprechen/VoiceRecorder';
import { CompactTranslationEye } from '@/components/common/CompactTranslationEye';
import { HoverTranslateText } from '@/components/common/HoverTranslateText';
import { cn } from '@/lib/utils';

interface Props { onBack:()=>void; onComplete:(score:number,total:number)=>void }
type Screen='home'|'teil1'|'teil2'|'teil3'|'free';
const OFFICIAL_T3_ORDER=['post','taxi','plate','receipt','key','shoes','bread','bottle','coins','timetable','sandwich','station'];

export function SpeakingModule({onBack,onComplete}:Props){
  const[screen,setScreen]=useState<Screen>('home');
  const[t2,setT2]=useState(0);const[t3,setT3]=useState(0);const[free,setFree]=useState(0);
  const[showSample,setShowSample]=useState(false);const[showGuide,setShowGuide]=useState(false);const[showTip,setShowTip]=useState(false);const[practiced,setPracticed]=useState(false);
  const t3Cards=useMemo(()=>[...speakingTeil3Cards].sort((a,b)=>rank(a.visual)-rank(b.visual)),[]);
  const reset=()=>{setShowSample(false);setShowGuide(false);setShowTip(false);setPracticed(false)};
  const openPart=(p:SpeakingPart)=>{reset();setScreen(`teil${p}` as Screen)};
  const home=()=>{reset();setScreen('home')};
  const recordEvaluation=(score:number)=>onComplete(score/100,1);

  if(screen==='home')return <div className="animate-fade-in"><Header onBack={onBack} subtitle="Sprechen A1" translation="Говорение"/><div className="mx-auto mb-6 max-w-2xl text-center"><p className="text-sm leading-6 text-slate-600">Trainieren Sie Sich vorstellen, Fragen stellen und Bitten formulieren. Deutsche Wörter können Sie antippen oder mit der Maus berühren, um die Übersetzung zu sehen.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><PartCard badge="T1" title="Sich vorstellen" description="Представьтесь по опорным словам." onClick={()=>openPart(1)}/><PartCard badge="T2" title="Informationen" description="Тема + слово: задайте простой вопрос." meta={`${speakingTeil2Cards.length} карточек`} onClick={()=>openPart(2)}/><PartCard badge="T3" title="Bitten" description="Картинка: сформулируйте просьбу и реакцию." meta={`${t3Cards.length} карточек`} onClick={()=>openPart(3)}/><PartCard badge="+" title="Freies Sprechen" description="Короткий рассказ по теме своими словами." meta={`${freeSpeakingTopics.length} тем`} onClick={()=>{reset();setScreen('free')}} accent/></div></div>;

  if(screen==='teil1')return <div className="animate-fade-in"><Header onBack={home} subtitle="T1 · Sich vorstellen" translation="Часть 1 · Представиться" onTip={()=>setShowTip(v=>!v)} tipOpen={showTip}/><InstructionBox german={speakingTeil1.instruction} russian={speakingTeil1.instructionRu}/>{showTip&&<ExaminerTipBox items={speakingTeil1.followUps}/>}<div className="mb-5 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="divide-y px-4 py-2 sm:px-6">{speakingTeil1.keywords.map(k=><div key={k} className="flex min-h-[64px] items-center justify-center py-3 text-center"><HoverTranslateText text={k} className="text-2xl font-bold sm:text-3xl"/></div>)}</div></div><VoiceRecorder evaluation={{mode:'teil1',expectedPoints:speakingTeil1.checkPoints}} onPracticed={()=>setPracticed(true)} onEvaluated={recordEvaluation}/><SampleBox show={showSample} onToggle={()=>setShowSample(v=>!v)} title="Beispiel"><p><HoverTranslateText text={speakingTeil1.sampleAnswer}/></p></SampleBox><BottomActions disabled={!practiced} onNext={home} nextLabel="Завершить T1"/></div>;

  if(screen==='teil2'){
    const card=speakingTeil2Cards[t2];
    return <div className="animate-fade-in"><Header onBack={home} subtitle={`T2 · Karte ${t2+1} von ${speakingTeil2Cards.length}`} translation="Часть 2 · Получение информации"/><InstructionBox german="Bitten Sie um Informationen. Stellen Sie eine Frage zum Thema und zum Wort auf der Karte." russian="Задайте партнёру простой вопрос по теме и слову на карточке."/><div className="mx-auto mb-5 max-w-xl overflow-hidden rounded-2xl border border-slate-400 bg-white shadow-sm"><ExamCardHeader label="T2"/><div className="flex items-center justify-between gap-3 border-b bg-slate-100 px-5 py-3"><span className="text-sm font-semibold text-slate-500">Thema</span><div className="min-w-0 flex-1 text-center text-lg font-bold"><HoverTranslateText text={card.theme}/></div><CompactTranslationEye parts={[card.theme,card.keyword]} translations={[card.themeRu,card.keywordRu]} title="Перевод карточки"/></div><div className="flex min-h-[190px] items-center justify-center px-6 py-10 text-center"><HoverTranslateText text={card.keyword} className="text-4xl font-black tracking-tight sm:text-5xl"/></div></div><VoiceRecorder evaluation={{mode:'teil2',theme:card.theme,keyword:card.keyword,sampleQuestion:card.sampleQuestion}} onPracticed={()=>setPracticed(true)} onEvaluated={recordEvaluation}/><SampleBox show={showSample} onToggle={()=>setShowSample(v=>!v)} title="Beispiel"><p className="font-medium"><HoverTranslateText text={`Frage: ${card.sampleQuestion}`}/></p><p className="mt-2"><HoverTranslateText text={`Antwort: ${card.sampleAnswer}`}/></p></SampleBox><BottomActions disabled={!practiced} onNext={()=>{setT2(v=>(v+1)%speakingTeil2Cards.length);reset()}} onShuffle={()=>{setT2(v=>nextRandomIndex(v,speakingTeil2Cards.length));reset()}} nextLabel="Следующая карточка" shuffleLabel="Случайная карточка"/></div>;
  }

  if(screen==='teil3'){
    const card=t3Cards[t3];
    return <div className="animate-fade-in"><Header onBack={home} subtitle={`T3 · Karte ${t3+1} von ${t3Cards.length}`} translation="Часть 3 · Просьбы"/><InstructionBox german="Formulieren Sie eine Bitte oder Frage zur Karte. Reagieren Sie auch auf eine Bitte Ihres Partners." russian="По картинке сформулируйте понятную просьбу или вопрос и короткую реакцию."/><div className="mx-auto mb-5 max-w-xl overflow-hidden rounded-2xl border-2 border-slate-800 bg-white shadow-md"><ExamCardHeader label="T3"/><div className="p-5 sm:p-7"><SpeakingCardIllustration visual={card.visual} alt={card.alt}/></div></div><VoiceRecorder evaluation={{mode:'teil3',object:card.alt,sampleRequest:card.sampleRequest}} onPracticed={()=>setPracticed(true)} onEvaluated={recordEvaluation}/><SampleBox show={showSample} onToggle={()=>setShowSample(v=>!v)} title="Beispiel"><p className="font-medium"><HoverTranslateText text={`Bitte: ${card.sampleRequest}`}/></p><p className="mt-2"><HoverTranslateText text={`Reaktion: ${card.sampleReaction}`}/></p></SampleBox><BottomActions disabled={!practiced} onNext={()=>{setT3(v=>(v+1)%t3Cards.length);reset()}} onShuffle={()=>{setT3(v=>nextRandomIndex(v,t3Cards.length));reset()}} nextLabel="Следующая карточка" shuffleLabel="Случайная карточка"/></div>;
  }

  const topic=freeSpeakingTopics[free];
  return <div className="animate-fade-in"><Header onBack={home} subtitle={`Freies Sprechen · Thema ${free+1} von ${freeSpeakingTopics.length}`} translation="Свободная речь"/><InstructionBox german="Sprechen Sie frei über das Thema. Nutzen Sie die Fragen nur als Hilfe." russian="Коротко расскажите по теме своими словами. Вопросы — только опора."/><div className="mb-5 overflow-hidden rounded-2xl border border-amber-200 bg-white shadow-sm"><div className="flex items-start justify-between gap-3 bg-amber-100 px-5 py-3"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wider text-amber-800">Freies Sprechen</p><h3 className="mt-1 text-xl font-black"><HoverTranslateText text={topic.title}/></h3></div><CompactTranslationEye parts={[topic.title]} translations={[topic.titleRu]} title="Перевод темы"/></div><div className="p-5"><div className="space-y-3">{topic.questions.map((q,i)=><div key={q} className="flex gap-3 rounded-xl bg-slate-50 p-3"><span className="font-black text-amber-700">{i+1}.</span><HoverTranslateText text={q}/></div>)}</div><button onClick={()=>setShowGuide(v=>!v)} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 font-bold text-amber-900"><Lightbulb className="h-4 w-4"/>{showGuide?'Скрыть конструктор':'Конструктор рассказа'}</button>{showGuide&&<div className="mt-4 rounded-xl border bg-white p-4">{topic.guide.map(line=><p key={line} className="border-b border-dashed py-2"><HoverTranslateText text={line}/></p>)}</div>}</div></div><VoiceRecorder evaluation={{mode:'free',title:topic.title,expectedPoints:topic.questions}} onPracticed={()=>setPracticed(true)} onEvaluated={recordEvaluation} hint="Говорите примерно 45–120 секунд."/><SampleBox show={showSample} onToggle={()=>setShowSample(v=>!v)} title="Beispiel"><p><HoverTranslateText text={topic.sample}/></p></SampleBox><BottomActions disabled={!practiced} onNext={()=>{setFree(v=>(v+1)%freeSpeakingTopics.length);reset()}} onShuffle={()=>{setFree(v=>nextRandomIndex(v,freeSpeakingTopics.length));reset()}} nextLabel="Следующая тема"/></div>;
}

function rank(visual:string){const i=OFFICIAL_T3_ORDER.indexOf(visual);return i===-1?OFFICIAL_T3_ORDER.length+speakingTeil3Cards.findIndex(c=>c.visual===visual):i}
function Header({onBack,subtitle,translation,onTip,tipOpen=false}:{onBack:()=>void;subtitle:string;translation:string;onTip?:()=>void;tipOpen?:boolean}){return <div className="mb-5 flex min-h-[68px] items-start gap-3"><button onClick={onBack} aria-label="Назад" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border bg-white"><ArrowLeft className="h-5 w-5"/></button><div className="min-w-0 flex-1 text-center"><h2 className="text-2xl font-black">Sprechen</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><div className="flex shrink-0 gap-2">{onTip&&<button onClick={onTip} aria-label="Подсказка экзаменатора" className={cn('flex h-11 w-11 items-center justify-center rounded-xl border',tipOpen?'bg-amber-50 text-amber-800':'bg-white')}><Lightbulb className="h-5 w-5"/></button>}<CompactTranslationEye parts={[subtitle]} translations={[translation]} title="Перевод"/></div></div>}
function PartCard({badge,title,description,meta,onClick,accent=false}:{badge:string;title:string;description:string;meta?:string;onClick:()=>void;accent?:boolean}){return <button onClick={onClick} className={cn('group min-h-[210px] rounded-2xl border bg-white p-5 text-left shadow-sm',accent?'border-amber-200':'border-slate-200')}><div className="mb-5 flex items-center justify-between"><span className={cn('flex h-10 min-w-10 items-center justify-center rounded-full px-2 text-sm font-bold',accent?'bg-amber-100 text-amber-900':'bg-slate-900 text-white')}>{badge}</span><ArrowRight className="h-5 w-5 text-slate-400"/></div><div className="text-lg font-bold"><HoverTranslateText text={title}/></div><p className="mt-2 text-[15px] leading-6 text-slate-600">{description}</p>{meta&&<p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-400">{meta}</p>}</button>}
function InstructionBox({german,russian}:{german:string;russian:string}){return <div className="mb-5 flex items-start justify-between gap-3 rounded-2xl border bg-slate-50 p-5"><p className="font-medium leading-7"><HoverTranslateText text={german}/></p><CompactTranslationEye parts={[german]} translations={[russian]} title="Перевод задания"/></div>}
function ExaminerTipBox({items}:{items:string[]}){return <div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 className="mb-3 text-center text-sm font-bold text-amber-900">Mögliche Fragen des Prüfers</h3><div className="space-y-2">{items.map(item=><div key={item} className="rounded-xl bg-white p-3 text-center"><HoverTranslateText text={item}/></div>)}</div></div>}
function ExamCardHeader({label}:{label:string}){return <div className="bg-slate-100 px-4 py-2 text-center text-xs font-bold uppercase tracking-[0.16em] text-slate-600">{label}</div>}
function SampleBox({show,onToggle,title,children}:{show:boolean;onToggle:()=>void;title:string;children:React.ReactNode}){return <div className="mb-5 rounded-2xl border bg-white p-5"><button onClick={onToggle} className="inline-flex items-center gap-2 text-sm font-semibold"><Eye className="h-4 w-4"/>{show?'Скрыть пример':'Показать пример после своего ответа'}</button>{show&&<div className="mt-4 rounded-xl bg-amber-50 p-4 text-[16px] leading-7"><div className="mb-2 text-xs font-bold uppercase text-amber-700">{title}</div>{children}</div>}</div>}
function BottomActions({disabled,onNext,onShuffle,nextLabel,shuffleLabel='Случайная тема'}:{disabled:boolean;onNext:()=>void;onShuffle?:()=>void;nextLabel:string;shuffleLabel?:string}){return <div className="flex flex-col-reverse gap-3 pb-8 sm:flex-row sm:justify-end">{onShuffle&&<button onClick={onShuffle} className="inline-flex min-h-[52px] items-center justify-center gap-2 rounded-xl border bg-white px-5 font-semibold"><RefreshCw className="h-4 w-4"/>{shuffleLabel}</button>}<button onClick={onNext} disabled={disabled} className={cn('inline-flex min-h-[52px] items-center justify-center gap-2 rounded-xl px-6 font-semibold',disabled?'bg-slate-100 text-slate-400':'bg-slate-900 text-white')}>{nextLabel}<ArrowRight className="h-4 w-4"/></button></div>}
function nextRandomIndex(current:number,total:number){if(total<=1)return 0;let next=current;while(next===current)next=Math.floor(Math.random()*total);return next}
