import { useMemo } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Clock3, Headphones, MessageCircleMore, PenLine } from 'lucide-react';
import type { ActivityEntry, ModuleId, Progress } from '@/types';
import { buildDailyPlan } from '@/lib/preparation';
import type { Minutes } from '@/components/Dashboard';
import { useUiLanguage } from '@/lib/i18n';

interface Props{minutes:Minutes;progress:Progress;activity:ActivityEntry[];onBack:()=>void;onSelectModule:(module:ModuleId)=>void}
const moduleIcons:Record<ModuleId,typeof PenLine>={schreiben:PenLine,sprechen:MessageCircleMore,lesen:BookOpen,horen:Headphones};
export function DailyTrainingPage({minutes,progress,activity,onBack,onSelectModule}:Props){const{lang,t}=useUiLanguage();const plan=useMemo(()=>buildDailyPlan(progress,minutes,activity),[progress,minutes,activity]);const firstTask=plan[0];return <div className="otto-roadmap-page animate-fade-in"><header className="otto-roadmap-page-header"><button type="button" onClick={onBack} className="otto-roadmap-back" aria-label={t('back')}><ArrowLeft/></button><div><span className="otto-roadmap-kicker">{t('today')}</span><h1>{t('trainingToday')}</h1></div><span className="otto-roadmap-time-badge"><Clock3/> {minutes} {t('minutes')}</span></header><section className="otto-roadmap-plan-card"><p className="otto-roadmap-plan-intro">{lang==='de'?'OTTO ordnet den Plan nach echten Ergebnissen, fehlenden Messdaten und aktuellen Schwächen.':'Отто собирает план по реальным результатам, недостатку данных и текущим слабым местам.'}</p><ol className="otto-roadmap-plan-list">{plan.map((item,index)=>{const Icon=moduleIcons[item.module];return <li key={`${item.module}-${index}`}><span className="otto-roadmap-plan-index">{index+1}</span><span className="otto-roadmap-plan-icon"><Icon/></span><span className="otto-roadmap-plan-text"><strong>{item.title}</strong><small>{item.detail}</small><small className="mt-1 text-slate-400">{item.reason}</small></span><span className="otto-roadmap-plan-minutes">{item.minutes} {t('minutes')}</span></li>})}</ol><button type="button" className="otto-roadmap-start" onClick={()=>firstTask&&onSelectModule(firstTask.module)} disabled={!firstTask}><span>{lang==='de'?'TRAINING STARTEN':'НАЧАТЬ ТРЕНИРОВКУ'}</span><ArrowRight/></button></section><button type="button" onClick={onBack} className="otto-roadmap-change-time">{lang==='de'?'Trainingszeit ändern':'Изменить время тренировки'}</button></div>}
