import { useMemo, useState } from 'react';
import { BarChart3,BookOpen,CheckCircle2,ChevronRight,Clock3,Headphones,Lightbulb,MessageCircleMore,PenLine,Sparkles,Trophy } from 'lucide-react';
import type { ActivityEntry,ModuleId,Progress } from '@/types';
import { getReadiness,getTodayActivity,MODULE_META,MODULE_ORDER } from '@/lib/preparation';
import { useUiLanguage } from '@/lib/i18n';
interface DashboardProps{onSelectModule:(module:ModuleId)=>void;onOpenInstructions:()=>void;onOpenExamGuide:()=>void;onOpenMockExam:()=>void;onOpenNews:()=>void;onOpenAccount:()=>void;onOpenSettings:()=>void;onOpenReadiness:()=>void;onShare:()=>void;onOpenSupport:()=>void;onOpenDailyTraining:(minutes:Minutes)=>void;onOpenHowTo:()=>void;progress:Progress;activity:ActivityEntry[]}
export type Minutes=5|15|30;
const moduleIcons:Record<ModuleId,typeof PenLine>={schreiben:PenLine,sprechen:MessageCircleMore,lesen:BookOpen,horen:Headphones};
const statusRu={ready:'готово',almost:'почти готово',train:'тренируем'} as const;const statusDe={ready:'bereit',almost:'fast bereit',train:'trainieren'} as const;
export function Dashboard({onSelectModule,onOpenInstructions,onOpenExamGuide,onOpenMockExam,onOpenSettings,onOpenReadiness,onOpenDailyTraining,onOpenHowTo,progress,activity}:DashboardProps){
 const{lang,t}=useUiLanguage();const[minutes,setMinutes]=useState<Minutes>(()=>{const s=Number(localStorage.getItem('otto-a1-session-minutes'));return s===5||s===15||s===30?s:15});const readiness=useMemo(()=>getReadiness(progress,activity),[progress,activity]);const today=useMemo(()=>getTodayActivity(activity),[activity]);
 const chooseMinutes=(value:Minutes)=>{setMinutes(value);try{localStorage.setItem('otto-a1-session-minutes',String(value))}catch{};onOpenDailyTraining(value)};
 const overall=readiness.overall;
 return <div className="otto-approved-dashboard otto-roadmap-dashboard animate-fade-in">
  <section className="otto-approved-hero" aria-labelledby="otto-home-title"><div className="otto-approved-hero-copy"><h1 id="otto-home-title" className="otto-approved-brand">Тренажёр Отто</h1><span className="otto-approved-brand-line" aria-hidden="true"/><h2>{lang==='de'?<>Mein Weg<br/>zum Zertifikat <em>A1</em></>:<>Мой путь<br/>к сертификату <em>A1</em></>}</h2><p>{lang==='de'?<>OTTO führt Sie Schritt für Schritt<br/>und zeigt, was heute<br/>am wichtigsten ist.</>:<>Отто ведёт вас по шагам и сам<br/>подсказывает, что лучше<br/>потренировать сегодня.</>}</p><span className="otto-approved-handwrite">Du schaffst das! ♡</span></div><span className="otto-approved-skyline" aria-hidden="true"/><div className="otto-approved-otto" aria-hidden="true"><img src="/otto/otto-home-documents.webp?v=2" className="otto-approved-otto-image" alt="" loading="eager" decoding="async" fetchPriority="high"/></div><span className="otto-approved-side-note" aria-hidden="true">Deutsch<br/>bringt dich<br/>weiter<br/>♡</span></section>
  <section className="otto-approved-readiness"><button type="button" onClick={onOpenReadiness} className="otto-approved-readiness-button"><span className="otto-approved-readiness-icon"><BarChart3/></span><span className="otto-approved-readiness-copy"><span className="otto-approved-readiness-top"><strong>{lang==='de'?'A1-BEREITSCHAFT':'ГОТОВНОСТЬ К A1'}</strong><b>{overall===null?'—':`${overall}%`}</b></span><span className="otto-approved-progress" aria-hidden="true"><i style={{width:`${overall??0}%`}}/></span><small>{readiness.evidenceLabel}</small></span><ChevronRight className="otto-approved-chevron"/></button></section>
  <section className="otto-approved-recommendation"><span className="otto-approved-recommendation-icon"><Sparkles/></span><div><strong>{lang==='de'?'OTTO EMPFIEHLT':'ОТТО РЕКОМЕНДУЕТ'}</strong><p>{readiness.recommendation}</p></div></section>
  <section className="otto-roadmap-training-picker" aria-labelledby="otto-training-picker-title"><div className="otto-roadmap-training-picker-head"><div><span>{t('today').toUpperCase()}</span><h2 id="otto-training-picker-title">{lang==='de'?'Ihr Training':'Ваша тренировка'}</h2></div><Clock3 aria-hidden="true"/></div><p className="otto-roadmap-training-picker-copy">{lang==='de'?'Wie viel Zeit haben Sie heute?':'Сколько времени хотите позаниматься сегодня?'}</p><div className="otto-roadmap-duration">{([5,15,30] as Minutes[]).map(value=><button key={value} type="button" onClick={()=>chooseMinutes(value)} className={minutes===value?'is-active':''} aria-pressed={minutes===value}><strong>{value}</strong><span>{t('minutes')}</span></button>)}</div></section>
  <button type="button" onClick={onOpenHowTo} className="otto-roadmap-howto-link"><span className="otto-roadmap-howto-icon"><Lightbulb/></span><span><strong>{t('howTo')}</strong><small>{lang==='de'?'Kurz erklärt: Tagesplan, Module und Prüfungstraining':'Коротко о программе Отто и самостоятельных занятиях'}</small></span><ChevronRight/></button>
  {(today.attempts>0||today.minutes>0)&&<section className="otto-approved-complete"><span><CheckCircle2/></span><div><strong>{lang==='de'?'Heute schon erledigt':'Сегодня уже сделано'}</strong><p>{today.attempts} {lang==='de'?'Versuche abgeschlossen':'завершённых попыток'}{today.minutes?` · ${today.minutes} ${t('minutes')}`:''}</p></div></section>}
  <section className="otto-approved-below-fold otto-premium-skills"><div className="otto-premium-section-heading"><div><p className="otto-premium-kicker">{lang==='de'?'Ihr Weg':'Ваш маршрут'}</p><h2>{lang==='de'?'Fertigkeiten bis zum Zertifikat':'Навыки до сертификата'}</h2></div><button type="button" onClick={onOpenReadiness} className="otto-premium-text-button">{lang==='de'?'Bereitschaftskarte':'Карта готовности'}</button></div><div className="otto-premium-skill-grid">{MODULE_ORDER.map(id=>{const m=readiness.modules[id],Icon=moduleIcons[id];return <button key={id} type="button" onClick={()=>onSelectModule(id)} className="otto-premium-skill-card"><span className="otto-premium-skill-top"><span className="otto-premium-skill-icon"><Icon/></span><span className="otto-premium-skill-score">{m.dataSufficient?`${m.score}%`:'—'}</span></span><strong>{MODULE_META[id].title}</strong><small>{lang==='de'?MODULE_META[id].title:MODULE_META[id].label}</small><span className="otto-premium-mini-progress" aria-hidden="true"><i style={{width:`${m.dataSufficient?m.score:0}%`}}/></span><span className={`otto-premium-status is-${m.status}`}>{m.dataSufficient?(lang==='de'?statusDe[m.status]:statusRu[m.status]):t('insufficient')}</span></button>})}</div></section>
  <section className="otto-premium-panel otto-premium-mock"><span className="otto-premium-mock-icon"><Trophy/></span><div className="otto-premium-mock-copy"><p className="otto-premium-kicker">{t('mockExam')}</p><h2>{readiness.mockLabel}</h2><p>{!readiness.dataSufficient?(lang==='de'?'OTTO zeigt noch keine Prüfungsbereitschaft, bis alle vier Fertigkeiten mehrfach gemessen wurden.':'Отто не показывает процент готовности, пока все четыре навыка не измерены несколькими реальными попытками.'):readiness.mockStatus==='recommended'?'Результаты достаточно устойчивы. Пора проверить себя целиком.':readiness.mockStatus==='try'?'Можно пройти пробник для диагностики, но Отто ещё видит слабые места.':`Сначала укрепите ${MODULE_META[readiness.weakest].title}.`}</p></div><button type="button" onClick={onOpenMockExam} className="otto-premium-secondary">{lang==='de'?'Probeprüfung öffnen':'Попробовать как на экзамене'} <ChevronRight/></button></section>
  <details className="otto-premium-details"><summary>{lang==='de'?'Bereich selbst wählen':'Хочу выбрать раздел сама'} <ChevronRight/></summary><div className="otto-premium-details-grid">{MODULE_ORDER.map(id=>{const Icon=moduleIcons[id];return <button key={id} type="button" onClick={()=>onSelectModule(id)}><Icon/><span>{MODULE_META[id].title}</span></button>})}</div></details>
  <details className="otto-premium-details"><summary>{lang==='de'?'Hilfsmaterialien':'Полезные материалы'} <ChevronRight/></summary><p className="otto-premium-details-note">{lang==='de'?'Hinweise sind direkt in die Übungen eingebaut.':'Подсказки встроены в тренировку. Здесь остаются материалы, к которым удобно вернуться отдельно.'}</p><div className="otto-premium-details-grid is-two"><button type="button" onClick={onOpenInstructions}><Lightbulb/><span>{lang==='de'?'Aufgaben bearbeiten':'Как выполнять задания'}</span></button><button type="button" onClick={onOpenExamGuide}><BookOpen/><span>{lang==='de'?'Prüfungsübersicht':'Справочник по экзамену'}</span></button></div></details><button type="button" onClick={onOpenSettings} className="sr-only">{t('settings')}</button>
 </div>
}
