import { useMemo, useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Headphones, Mic, PenTool, Printer, Search, Sparkles, Volume2 } from 'lucide-react';
import { HoverTranslateText } from '@/components/common/HoverTranslateText';

interface ExamGuideProps { onBack: () => void }
type Page = 'menu' | 'plan' | 'schreiben' | 'horen' | 'sprechen' | 'grammar' | 'words' | 'alphabet' | 'weekdays' | 'months' | 'time-dates' | 'numbers' | 'phone-prices' | 'nicht-kein' | 'aber-leider';
type Row = string[];

const verbs: Row[] = [['sein','быть'],['haben','иметь'],['heißen','называться'],['kommen','приходить / приезжать'],['wohnen','жить'],['sprechen','говорить'],['lernen','учить'],['arbeiten','работать'],['machen','делать'],['gehen','идти'],['fahren','ехать'],['bleiben','оставаться'],['essen','есть'],['trinken','пить'],['kaufen','покупать'],['bezahlen','платить'],['finden','находить'],['suchen','искать'],['brauchen','нуждаться'],['möchten','хотеть вежливо'],['können','мочь'],['müssen','быть должным'],['helfen','помогать'],['treffen','встречаться'],['besuchen','посещать'],['schreiben','писать'],['lesen','читать'],['bringen','приносить']];
const nouns: Row[] = [['die Familie','семья'],['der Freund','друг'],['die Freundin','подруга'],['das Kind','ребёнок'],['die Wohnung','квартира'],['das Zimmer','комната'],['die Stadt','город'],['die Straße','улица'],['der Bahnhof','вокзал'],['die Schule','школа'],['die Arbeit','работа'],['der Beruf','профессия'],['der Arzt','врач'],['die Apotheke','аптека'],['das Restaurant','ресторан'],['das Hotel','гостиница'],['der Supermarkt','супермаркет'],['die Bäckerei','пекарня'],['die Post','почта'],['die Bank','банк'],['der Bus','автобус'],['der Zug','поезд'],['das Taxi','такси'],['das Fahrrad','велосипед'],['die Fahrkarte','билет'],['das Geld','деньги'],['die Zeit','время'],['die Uhr','часы / время'],['das Essen','еда'],['das Wasser','вода'],['das Brot','хлеб'],['das Geschenk','подарок']];
const questions: Row[] = [['Wer?','Кто?'],['Was?','Что?'],['Wo?','Где?'],['Wohin?','Куда?'],['Woher?','Откуда?'],['Wann?','Когда?'],['Wie?','Как?'],['Warum?','Почему?'],['Wie viel?','Сколько?'],['Wie lange?','Как долго?'],['Wie alt?','Сколько лет?'],['Welche?','Какой / какая / какие?']];
const alphabet: Row[] = [['A','а'],['B','бэ'],['C','цэ'],['D','дэ'],['E','э'],['F','эф'],['G','гэ'],['H','ха'],['I','и'],['J','йот'],['K','ка'],['L','эль'],['M','эм'],['N','эн'],['O','о'],['P','пэ'],['Q','ку'],['R','эр'],['S','эс'],['T','тэ'],['U','у'],['V','фау'],['W','вэ'],['X','икс'],['Y','юпсилон'],['Z','цэт'],['Ä','э'],['Ö','ё'],['Ü','ю'],['ß','эс-цэт']];
const weekdays: Row[] = [['Montag','мо́нтаг','понедельник'],['Dienstag','ди́нстаг','вторник'],['Mittwoch','ми́твох','среда'],['Donnerstag','до́нэрстаг','четверг'],['Freitag','фра́йтаг','пятница'],['Samstag','за́мстаг','суббота'],['Sonntag','зо́нтаг','воскресенье']];
const months: Row[] = [['Januar','я́нуар','январь'],['Februar','фе́бруар','февраль'],['März','мэрц','март'],['April','апри́ль','апрель'],['Mai','май','май'],['Juni','ю́ни','июнь'],['Juli','ю́ли','июль'],['August','аугу́ст','август'],['September','зэптэ́мба','сентябрь'],['Oktober','окто́ба','октябрь'],['November','новэ́мба','ноябрь'],['Dezember','дэцэ́мба','декабрь']];
const timeDates: Row[] = [['Wie spät ist es?','ви шпэт ист эс?','Который час?'],['Es ist acht Uhr.','эс ист ахт у́а','Сейчас восемь часов.'],['halb neun','хальб нойн','половина девятого / 8:30'],['Viertel nach acht','фи́ртель нах ахт','четверть девятого / 8:15'],['Viertel vor neun','фи́ртель фор нойн','без четверти девять / 8:45'],['am Montag','ам мо́нтаг','в понедельник'],['am 3. Mai','ам дри́ттэн май','3 мая'],['im September','им зэптэ́мба','в сентябре'],['um 18 Uhr','ум ахтцэйн у́а','в 18:00'],['heute','хо́йте','сегодня'],['morgen','мо́рген','завтра'],['gestern','гэ́стэрн','вчера']];
const phonePrices: Row[] = [['Wie ist Ihre Telefonnummer?','ви ист и́рэ тэлефо́ннумэр?','Какой у Вас номер телефона?'],['null eins sieben sechs …','нуль айнс зи́бэн зэкс…','0 1 7 6 …'],['Wie viel kostet das?','ви филь ко́стэт дас?','Сколько это стоит?'],['Das kostet zwölf Euro fünfzig.','дас ко́стэт цвёльф о́йро фю́нфцих','Это стоит 12 евро 50 центов.'],['19,95 €','нойнцэйн о́йро фю́нф-унт-нойнцих','19 евро 95 центов']];
const nichtKein: Row[] = [['nicht','нихт','не — отрицает действие, признак или обстоятельство'],['Ich komme nicht.','их ко́мэ нихт','Я не приду.'],['Das ist nicht teuer.','дас ист нихт то́йа','Это не дорого.'],['kein','кайн','нет / никакой — отрицает существительное'],['Ich habe kein Auto.','их ха́бэ кайн а́уто','У меня нет машины.'],['Ich habe keine Zeit.','их ха́бэ ка́йнэ цайт','У меня нет времени.']];
const aberLeider: Row[] = [['aber','а́ба','но — противопоставление'],['Ich komme, aber später.','их ко́мэ, а́ба шпэ́та','Я приду, но позже.'],['leider','ла́йда','к сожалению'],['Leider kann ich nicht kommen.','ла́йда кан их нихт ко́мэн','К сожалению, я не могу прийти.'],['Aber leider …','а́ба ла́йда','Но, к сожалению…']];

const basic: Record<number,[string,string,string]> = {
  0:['null','нуль','ноль'],1:['eins','айнс','один'],2:['zwei','цвай','два'],3:['drei','драй','три'],4:['vier','фир','четыре'],5:['fünf','фюнф','пять'],6:['sechs','зэкс','шесть'],7:['sieben','зи́бен','семь'],8:['acht','ахт','восемь'],9:['neun','нойн','девять'],10:['zehn','цэйн','десять'],11:['elf','эльф','одиннадцать'],12:['zwölf','цвёльф','двенадцать'],13:['dreizehn','драйцэйн','тринадцать'],14:['vierzehn','фирцэйн','четырнадцать'],15:['fünfzehn','фюнфцэйн','пятнадцать'],16:['sechzehn','зэхцэйн','шестнадцать'],17:['siebzehn','зибцэйн','семнадцать'],18:['achtzehn','ахтцэйн','восемнадцать'],19:['neunzehn','нойнцэйн','девятнадцать'],20:['zwanzig','цва́нцих','двадцать'],30:['dreißig','дра́йсих','тридцать'],40:['vierzig','фи́рцих','сорок'],50:['fünfzig','фю́нфцих','пятьдесят'],60:['sechzig','зэ́хцих','шестьдесят'],70:['siebzig','зи́бцих','семьдесят'],80:['achtzig','а́хтцих','восемьдесят'],90:['neunzig','но́йнцих','девяносто'],100:['hundert','ху́ндэрт','сто']
};
const tensRu: Record<number,string> = {20:'двадцать',30:'тридцать',40:'сорок',50:'пятьдесят',60:'шестьдесят',70:'семьдесят',80:'восемьдесят',90:'девяносто'};
const units: Record<number,[string,string]> = {1:['ein','айн'],2:['zwei','цвай'],3:['drei','драй'],4:['vier','фир'],5:['fünf','фюнф'],6:['sechs','зэкс'],7:['sieben','зи́бен'],8:['acht','ахт'],9:['neun','нойн']};
function numberRow(n:number): Row {
  const direct = basic[n];
  if (direct) return [String(n), direct[0], direct[1], direct[2]];
  const ten = Math.floor(n/10)*10;
  const unit = n%10;
  const [unitDe,unitTr] = units[unit];
  const [tenDe,tenTr] = basic[ten];
  return [String(n),`${unitDe}und${tenDe}`,`${unitTr}-унт-${tenTr}`,`${tensRu[ten]} ${basic[unit][2]}`];
}
const allNumbers = Array.from({length:101},(_,n)=>numberRow(n));

export function ExamGuide({onBack}:ExamGuideProps) {
  const [page,setPage] = useState<Page>('menu');
  if(page==='menu') return <GuideMenu onBack={onBack} onOpen={setPage}/>;
  if(page==='plan') return <DetailShell title="Как готовиться" onBack={()=>setPage('menu')}><Plan/></DetailShell>;
  if(page==='schreiben') return <DetailShell title="Гайд Schreiben" onBack={()=>setPage('menu')}><SchreibenGuide/></DetailShell>;
  if(page==='horen') return <DetailShell title="Гайд Hören" onBack={()=>setPage('menu')}><HorenGuide onOpen={setPage}/></DetailShell>;
  if(page==='sprechen') return <DetailShell title="Гайд Sprechen" onBack={()=>setPage('menu')}><SprechenGuide onOpen={setPage}/></DetailShell>;
  if(page==='grammar') return <DetailShell title="Грамматика A1" onBack={()=>setPage('menu')}><Grammar/></DetailShell>;
  if(page==='words') return <DetailShell title="Мини-словарь A1" onBack={()=>setPage('menu')}><WordLists/></DetailShell>;
  if(page==='alphabet') return <DetailShell title="Немецкий алфавит" onBack={()=>setPage('sprechen')}><SimpleTable rows={alphabet} headers={['Буква','Русская транскрипция']}/><PrintButton/></DetailShell>;
  if(page==='numbers') return <DetailShell title="Числа 0–100" onBack={()=>setPage('horen')}><NumbersTable/><PrintButton/></DetailShell>;
  const detailMap:Record<string,{title:string;rows:Row[]}> = {weekdays:{title:'Дни недели',rows:weekdays},months:{title:'Месяцы',rows:months},'time-dates':{title:'Время и даты',rows:timeDates},'phone-prices':{title:'Телефонные номера и цены',rows:phonePrices},'nicht-kein':{title:'nicht и kein',rows:nichtKein},'aber-leider':{title:'aber и leider',rows:aberLeider}};
  const detail = detailMap[page];
  return <DetailShell title={detail.title} onBack={()=>setPage('horen')}><SimpleTable rows={detail.rows} headers={['Немецкий','Русская транскрипция','Перевод на русский']}/><PrintButton/></DetailShell>;
}

function GuideMenu({onBack,onOpen}:{onBack:()=>void;onOpen:(p:Page)=>void}) { const items=[['plan','Как готовиться','План занятий и распределение времени',Sparkles],['schreiben','Schreiben','Письмо, формуляр, готовые фразы',PenTool],['horen','Hören','Что слушать и что запомнить',Headphones],['sprechen','Sprechen','Алфавит, слова, вопросы и речь',Mic],['grammar','Грамматика A1','Только базовые конструкции',BookOpen],['words','Мини-словарь','Самые нужные слова для экзамена',Search]] as const; return <div className="animate-fade-in pb-8"><div className="mb-6 flex items-center gap-3"><Back onClick={onBack}/><div><p className="text-sm font-semibold text-teal-700">База Отто</p><h1 className="text-2xl font-black">Гайды и помощники</h1></div></div><div className="mx-auto max-w-2xl space-y-3">{items.map(([id,title,desc,Icon])=><button key={id} onClick={()=>onOpen(id)} className="flex w-full items-center gap-4 rounded-2xl border bg-white p-4 text-left shadow-sm"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-teal-50"><Icon className="h-6 w-6 text-teal-700"/></span><span className="flex-1"><b>{title}</b><span className="mt-1 block text-sm text-slate-500">{desc}</span></span><ArrowRight className="h-5 w-5 text-slate-400"/></button>)}</div></div> }
function DetailShell({title,onBack,children}:{title:string;onBack:()=>void;children:ReactNode}) { return <div className="animate-fade-in pb-10"><div className="mb-5 flex items-center gap-3"><Back onClick={onBack}/><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-wider text-teal-700">Помощник Отто</p><h1 className="truncate text-2xl font-black">{title}</h1></div><img src="/otto.png" alt="Отто" className="h-14 w-14 shrink-0 object-contain"/></div>{children}</div> }
function Plan(){return <div className="space-y-5"><Hero title="Коротко, регулярно, по формату экзамена" text="Слова → слушание → тренировка Отто по всем модулям → повтор ошибок."/><div className="grid gap-3 sm:grid-cols-2"><Time time="10–15 мин" title="Слова" text="готовые сочетания и полезные фразы"/><Time time="15–20 мин" title="Hören" text="слушать и запоминать: числа, время, короткие диалоги"/><Time time="20–30 мин" title="Отто" text="занятия по всем модулям: Lesen, Hören, Schreiben, Sprechen"/><Time time="5–10 мин" title="Повтор" text="ошибки и фразы, которые пока не получаются"/></div></div>}
function SchreibenGuide(){const phrases=['Sehr geehrte Damen und Herren,','Liebe Anna, / Lieber Peter,','Ich möchte mich für den Kurs anmelden.','Wann beginnt der Kurs?','Wie viel kostet der Kurs?','Können Sie mir bitte Informationen schicken?','Ich kann leider nicht kommen.','Ich freue mich auf Ihre Antwort.','Mit freundlichen Grüßen','Viele Grüße'];return <div className="space-y-5"><Hero title="Письмо A1: просто и по трём пунктам" text="Ответьте на каждый пункт, добавьте обращение и прощание."/><div className="rounded-2xl border bg-white p-5"><h2 className="font-black">Полезные фразы</h2><p className="mt-1 text-xs text-slate-500">Наведи на немецкое слово — перевод появится сверху.</p><div className="mt-4 space-y-2">{phrases.map(p=><div key={p} className="rounded-xl bg-slate-50 px-4 py-3"><HoverTranslateText text={p}/></div>)}</div></div><PrintButton/></div>}
function HorenGuide({onOpen}:{onOpen:(p:Page)=>void}){const items:[Page,string,string][]=[['weekdays','Дни недели','произношение + перевод'],['months','Месяцы','произношение + перевод'],['time-dates','Время и даты','частые формулировки'],['numbers','Числа 0–100','все числа + поиск'],['phone-prices','Телефон и цены','цифры на слух'],['nicht-kein','nicht и kein','отрицание'],['aber-leider','aber и leider','изменение смысла']];return <div className="space-y-5"><Hero title="Hören: слушайте ключевую информацию" text="Главное — услышать число, время, дату, место, цену, отрицание и изменение планов."/><div className="grid gap-3 sm:grid-cols-2">{items.map(([id,title,meta])=><button key={id} onClick={()=>onOpen(id)} className="flex min-h-[68px] items-center justify-between rounded-xl border border-sky-200 bg-white px-4 py-3 text-left"><span><b>{title}</b><span className="block text-xs text-slate-500">{meta}</span></span><ArrowRight className="h-4 w-4 text-sky-700"/></button>)}</div></div>}
function SprechenGuide({onOpen}:{onOpen:(p:Page)=>void}){return <div className="space-y-5"><Hero title="Sprechen: короткая понятная речь" text="Представьтесь, задайте простой вопрос и сформулируйте вежливую просьбу."/><button onClick={()=>onOpen('alphabet')} className="flex w-full items-center gap-4 rounded-2xl border border-rose-200 bg-white p-5 text-left"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-rose-50"><Volume2 className="h-6 w-6 text-rose-700"/></span><span className="flex-1"><b>Немецкий алфавит и произношение</b><span className="block text-sm text-slate-500">Русская транскрипция + печать</span></span><ArrowRight className="h-5 w-5"/></button><WordTable title="Существительные" rows={nouns}/><WordTable title="Глаголы" rows={verbs}/><WordTable title="Вопросы" rows={questions}/><PrintButton/></div>}
function Grammar(){return <div className="space-y-4"><Hero title="Только базовые конструкции A1" text="Сначала уверенно стройте простое предложение и вопрос."/><SimpleTable headers={['Конструкция','Формула','Пример']} rows={[["Обычное предложение","Подлежащее + глагол + остальное","Ich lerne Deutsch."],["W-вопрос","Вопросительное слово + глагол + подлежащее","Wo wohnen Sie?"],["Да/нет","Глагол + подлежащее + остальное","Kommen Sie heute?"],["Модальный глагол","Подлежащее + Modalverb + … + Infinitiv","Ich kann heute kommen."]]}/></div>}
function WordLists(){return <div className="space-y-5"><Hero title="Мини-словарь Отто" text="Повторяйте небольшими блоками и используйте слова в коротких фразах."/><WordTable title="Существительные" rows={nouns}/><WordTable title="Глаголы" rows={verbs}/><WordTable title="Вопросительные слова" rows={questions}/></div>}
function NumbersTable(){const[q,setQ]=useState('');const rows=useMemo(()=>{const s=q.trim().toLocaleLowerCase('ru-RU');return s?allNumbers.filter(r=>r.join(' ').toLocaleLowerCase('ru-RU').includes(s)):allNumbers},[q]);return <div className="space-y-3"><div className="sticky top-[78px] z-20 rounded-2xl border bg-white p-3 shadow-sm"><label className="flex items-center gap-2"><Search className="h-5 w-5 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Введите 27, sieben, зибен…" className="min-h-11 w-full border-0 bg-transparent outline-none"/></label></div><SimpleTable rows={rows} headers={['Число','Немецкий','Русская транскрипция','Перевод на русский']}/></div>}
function SimpleTable({rows,headers}:{rows:Row[];headers:string[]}){return <div className="mb-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-slate-900 text-white"><tr>{headers.map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,i)=><tr key={`${row[0]}-${i}`}>{row.map((cell,j)=><td key={j} className="px-4 py-3 leading-6 text-slate-700">{j===0&&headers[0]!=='Число'?<HoverTranslateText text={cell}/>:cell}</td>)}</tr>)}</tbody></table></div>}
function WordTable({title,rows}:{title:string;rows:Row[]}){return <div className="rounded-2xl border bg-white p-5"><h2 className="font-black">{title}</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{rows.map(([de,ru])=><div key={de} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-3 py-2"><HoverTranslateText text={de}/><span className="text-right text-slate-500">{ru}</span></div>)}</div></div>}
function Hero({title,text}:{title:string;text:string}){return <div className="rounded-2xl bg-gradient-to-br from-slate-900 to-slate-800 p-5 text-white"><h2 className="text-xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-white/75">{text}</p></div>}
function Time({time,title,text}:{time:string;title:string;text:string}){return <div className="rounded-2xl border bg-white p-4"><span className="text-xs font-black uppercase tracking-wider text-teal-700">{time}</span><h3 className="mt-1 font-black">{title}</h3><p className="mt-1 text-sm text-slate-600">{text}</p></div>}
function PrintButton(){return <button type="button" onClick={()=>window.print()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white"><Printer className="h-4 w-4"/>Распечатать / сохранить как PDF</button>}
function Back({onClick}:{onClick:()=>void}){return <button type="button" onClick={onClick} aria-label="Назад" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border bg-white"><ArrowLeft className="h-5 w-5"/></button>}
