import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock, Headphones, Loader2, Mic, Pause, Play, RotateCcw, Square, Trophy } from 'lucide-react';
import { listeningTasks, type HorenTask } from '@/data/listening';
import { loadLesenArchive, type LesenArchiveData, type LesenArchiveOption } from '@/data/lesen/archiveData';
import { schreibenTeil1Tasks } from '@/data/schreiben/teil1';
import { schreibenTeil2Tasks } from '@/data/schreiben/teil2';
import { speakingTeil1, speakingTeil2Cards } from '@/data/speaking';
import { speakingTeil3ArchiveCards } from '@/data/speakingTeil3Archive';
import { Teil3ArchiveImage } from '@/components/sprechen/Teil3ArchiveImage';
import { buildMockAttempt, saveMockAttempt, type MockAttempt } from '@/lib/mockExam';
import type { ModuleId } from '@/types';
import { cn } from '@/lib/utils';

type ExamStage='menu'|'horen'|'lesen'|'schreiben'|'sprechen'|'result';
type SectionStage=Exclude<ExamStage,'menu'|'result'>;
type RawResult={raw:number;rawMax:number};
interface Props{onBack:()=>void;onRecordModule?:(module:ModuleId,percent:number)=>void}
const DURATIONS:Record<SectionStage,number>={horen:20*60,lesen:25*60,schreiben:20*60,sprechen:15*60};
const ORDER:SectionStage[]=['horen','lesen','schreiben','sprechen'];
const SECTION_LABEL:Record<SectionStage,string>={horen:'Hören',lesen:'Lesen',schreiben:'Schreiben',sprechen:'Sprechen'};

export function MockExam({onBack,onRecordModule}:Props){
 const[stage,setStage]=useState<ExamStage>('menu');const[time,setTime]=useState(0);const[results,setResults]=useState<Partial<Record<SectionStage,RawResult>>>({});const[expired,setExpired]=useState<Partial<Record<SectionStage,boolean>>>({});const[runId,setRunId]=useState(()=>`mock-${Date.now()}-${Math.random().toString(36).slice(2,8)}`);const[requestSet,setRequestSet]=useState(()=>Math.floor(Math.random()*10));const[finalAttempt,setFinalAttempt]=useState<MockAttempt|null>(null);const reportedRef=useRef(false);
 useEffect(()=>{if(!ORDER.includes(stage as SectionStage)||time<=0)return;const id=window.setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>window.clearInterval(id)},[stage,time]);
 const start=(s:SectionStage)=>{if(expired[s])return;setStage(s);setTime(DURATIONS[s]);window.scrollTo({top:0})};
 const lockSection=(s:SectionStage)=>setExpired(prev=>prev[s]?prev:{...prev,[s]:true});
 const finishSection=(s:SectionStage,result:RawResult)=>{setResults(prev=>({...prev,[s]:result}));setStage('menu');window.scrollTo({top:0})};
 const allDone=ORDER.every(id=>Boolean(results[id]));
 const showResult=()=>{if(!allDone)return;const raw=results as Record<SectionStage,RawResult>;const attempt=buildMockAttempt(runId,{horen:raw.horen,lesen:raw.lesen,schreiben:raw.schreiben,sprechen:raw.sprechen});saveMockAttempt(attempt);setFinalAttempt(attempt);if(!reportedRef.current&&onRecordModule){reportedRef.current=true;(['horen','lesen','schreiben','sprechen'] as ModuleId[]).forEach(id=>onRecordModule(id,Math.round(attempt.sections[id].points/25*100)))}setStage('result');window.scrollTo({top:0})};
 const restart=()=>{setStage('menu');setTime(0);setResults({});setExpired({});setFinalAttempt(null);setRunId(`mock-${Date.now()}-${Math.random().toString(36).slice(2,8)}`);setRequestSet(Math.floor(Math.random()*10));reportedRef.current=false};
 if(stage==='result'&&finalAttempt)return <FinalResult attempt={finalAttempt} onBack={onBack} onRestart={restart}/>;
 if(stage==='menu')return <div className="animate-fade-in pb-8"><Header onBack={onBack}/><section className="rounded-3xl bg-slate-950 p-6 text-white"><Trophy className="h-10 w-10 text-amber-300"/><h2 className="mt-3 text-2xl font-black">Пробный экзамен Goethe A1</h2><p className="mt-2 text-sm leading-6 text-white/75">Структура и шкала соответствуют актуальному официальному Modelltest: Hören 15 заданий, Lesen 15, Schreiben 2 части и Sprechen 3 части. Итог — 100 баллов, проходной порог 60.</p><p className="mt-2 text-xs leading-5 text-white/55">Во время частей правильные ответы и баллы не показываются. Итог и рекомендации появятся только после завершения всех четырёх разделов.</p></section><div className="mt-5 grid gap-3 sm:grid-cols-2">{ORDER.map(id=>{const locked=Boolean(expired[id]);return <button key={id} onClick={()=>start(id)} disabled={locked} className={cn('rounded-2xl border p-5 text-left shadow-sm transition',locked?'cursor-not-allowed border-rose-200 bg-rose-50 opacity-80':'border-slate-200 bg-white hover:border-teal-300')}><div className="flex items-center justify-between"><b className="text-lg text-slate-950">{SECTION_LABEL[id]}</b>{locked?<Clock className="h-5 w-5 text-rose-600"/>:results[id]&&<CheckCircle2 className="h-5 w-5 text-emerald-600"/>}</div><p className="mt-1 text-sm text-slate-500">≈ {Math.round(DURATIONS[id]/60)} минут</p><span className={cn('mt-4 inline-block font-bold',locked?'text-rose-700':'text-teal-700')}>{locked?'Время закончилось':results[id]?'Пройти ещё раз':'Начать'}{!locked?' →':''}</span>{locked&&<small className="mt-2 block leading-5 text-rose-700">Эта часть закрыта до начала нового пробного экзамена.</small>}</button>})}</div>{allDone&&<button onClick={showResult} className="mt-5 min-h-12 w-full rounded-xl bg-teal-700 px-5 font-black text-white">Показать итог экзамена</button>}</div>;
 if(stage==='horen')return <HorenMock time={time} onBack={()=>setStage('menu')} onExpire={()=>lockSection('horen')} onFinish={r=>finishSection('horen',r)}/>;
 if(stage==='lesen')return <LesenMock time={time} onBack={()=>setStage('menu')} onExpire={()=>lockSection('lesen')} onFinish={r=>finishSection('lesen',r)}/>;
 if(stage==='schreiben')return <SchreibenMock time={time} onBack={()=>setStage('menu')} onExpire={()=>lockSection('schreiben')} onFinish={r=>finishSection('schreiben',r)}/>;
 return <SprechenMock time={time} setIndex={requestSet} onBack={()=>setStage('menu')} onExpire={()=>lockSection('sprechen')} onFinish={r=>finishSection('sprechen',r)}/>;
}

function Shell({stage,time,onBack,children,onFinish,onExpire,finishDisabled=false,finishLoading=false}:{stage:SectionStage;time:number;onBack:()=>void;children:React.ReactNode;onFinish:(timedOut?:boolean)=>void|Promise<void>;onExpire:()=>void;finishDisabled?:boolean;finishLoading?:boolean}){const expiredOnce=useRef(false);useEffect(()=>{if(time!==0||expiredOnce.current)return;expiredOnce.current=true;onExpire();void onFinish(true)},[time,onExpire,onFinish]);return <div className="animate-fade-in pb-8"><div className="sticky top-0 z-30 -mx-4 mb-5 flex items-center justify-between gap-3 border-b border-slate-200 bg-[#f7f4ee]/95 px-4 py-3 backdrop-blur"><button onClick={onBack} disabled={time===0} className="flex h-10 w-10 items-center justify-center rounded-xl border bg-white disabled:cursor-not-allowed disabled:opacity-40" aria-label="Назад"><ArrowLeft className="h-5 w-5"/></button><b className="text-lg">{SECTION_LABEL[stage]}</b><span className={cn('inline-flex items-center gap-2 rounded-xl px-3 py-2 font-mono font-bold',time<60?'bg-rose-100 text-rose-700':'bg-slate-900 text-white')}><Clock className="h-4 w-4"/>{fmt(time)}</span></div>{children}<button onClick={()=>void onFinish(false)} disabled={finishDisabled||finishLoading||time===0} className="mt-6 min-h-12 w-full rounded-xl bg-slate-900 px-5 font-bold text-white disabled:opacity-40">{finishLoading?'Сохраняем результат…':'Завершить часть'}</button>{time===0&&<p className="mt-2 text-center text-sm font-bold text-rose-700">Время закончилось. Эта часть закрывается, незавершённые ответы считаются пропущенными.</p>}</div>}

function HorenMock({time,onBack,onExpire,onFinish}:{time:number;onBack:()=>void;onExpire:()=>void;onFinish:(r:RawResult)=>void}){const items=useMemo(()=>listeningTasks.slice(0,15),[]);const[answers,setAnswers]=useState<Record<number,number|boolean>>({});const finish=()=>{const raw=items.reduce((sum,t,i)=>sum+(answerCorrect(t,answers[i])?1:0),0);onFinish({raw,rawMax:15})};return <Shell stage="horen" time={time} onBack={onBack} onExpire={onExpire} onFinish={finish}><div className="mb-4 rounded-xl bg-sky-50 p-4 text-sm leading-6 text-sky-900">Teil 1: Aufgaben 1–6 — два прослушивания. Teil 2: 7–10 — одно. Teil 3: 11–15 — два. Следите за количеством доступных прослушиваний для каждой части.</div><div className="space-y-4">{items.map((task,index)=><ExamAudioQuestion key={task.id} task={task} limit={index<6?2:index<10?1:2} answer={answers[index]??null} onAnswer={value=>setAnswers(prev=>({...prev,[index]:value}))}/>)}</div></Shell>}
function ExamAudioQuestion({task,limit,answer,onAnswer}:{task:HorenTask;limit:number;answer:number|boolean|null;onAnswer:(v:number|boolean)=>void}){const[plays,setPlays]=useState(0);const[playing,setPlaying]=useState(false);const[failed,setFailed]=useState(false);const audioRef=useRef<HTMLAudioElement|null>(null);const src=`/audio/${String(task.number).padStart(3,'0')}.mp3`;const play=()=>{const a=audioRef.current;if(!a||plays>=limit)return;a.currentTime=0;a.play().then(()=>{setPlaying(true);setPlays(v=>v+1)}).catch(()=>setFailed(true))};const stop=()=>{audioRef.current?.pause();setPlaying(false)};return <div className="rounded-2xl border bg-white p-4"><audio ref={audioRef} src={src} preload="metadata" onEnded={()=>setPlaying(false)} onError={()=>setFailed(true)}/><div className="flex items-center justify-between gap-2"><span className="text-xs font-black uppercase text-sky-700">Aufgabe {task.number}</span><span className="text-xs text-slate-500">{plays}/{limit}</span></div><button disabled={plays>=limit&&!playing||failed} onClick={playing?stop:play} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-xl bg-sky-50 px-3 text-sm font-bold text-sky-800 disabled:opacity-40">{playing?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}{failed?'Аудио недоступно':playing?'Стоп':'Слушать'}</button><p className="mt-3 font-semibold">{task.prompt}</p><div className="mt-3 grid gap-2">{task.type==='multiple-choice'?task.options.map((option,n)=><button key={`${option}-${n}`} onClick={()=>onAnswer(n)} className={examChoice(answer===n)}>{String.fromCharCode(65+n)}. {option}</button>):([true,false] as boolean[]).map(value=><button key={String(value)} onClick={()=>onAnswer(value)} className={examChoice(answer===value)}>{value?'Richtig':'Falsch'}</button>)}</div></div>}
function answerCorrect(task:HorenTask,answer:number|boolean|undefined){return task.type==='multiple-choice'?answer===task.correctIndex:answer===task.correctAnswer}

interface LesenExamItem{id:string;part:1|2|3;context:string;prompt:string;options:Array<{value:string;label:string}>;correct:string}
function LesenMock({time,onBack,onExpire,onFinish}:{time:number;onBack:()=>void;onExpire:()=>void;onFinish:(r:RawResult)=>void}){const[data,setData]=useState<LesenArchiveData|null>(null);const[error,setError]=useState('');const[answers,setAnswers]=useState<Record<string,string>>({});useEffect(()=>{let live=true;loadLesenArchive().then(v=>live&&setData(v)).catch(e=>live&&setError(e instanceof Error?e.message:'Не удалось загрузить задания Lesen.'));return()=>{live=false}},[]);const items=useMemo(()=>data?buildLesenItems(data):[],[data]);const finish=()=>onFinish({raw:items.reduce((s,x)=>s+(answers[x.id]===x.correct?1:0),0),rawMax:15});return <Shell stage="lesen" time={time} onBack={onBack} onExpire={onExpire} onFinish={finish} finishDisabled={!data}>{!data&&!error&&<div className="py-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin"/><p className="mt-3">Загружаю экзаменационные задания…</p></div>}{error&&<p className="rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}<div className="space-y-4">{items.map((item,index)=><div key={item.id} className="rounded-2xl border bg-white p-4"><p className="text-xs font-black uppercase tracking-wider text-teal-700">Lesen · Teil {item.part} · Aufgabe {index+1}</p><div className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{item.context}</div><p className="mt-4 font-semibold leading-6">{item.prompt}</p><div className="mt-3 grid gap-2">{item.options.map(opt=><button key={opt.value} onClick={()=>setAnswers(prev=>({...prev,[item.id]:opt.value}))} className={examChoice(answers[item.id]===opt.value)}>{opt.label}</button>)}</div></div>)}</div></Shell>}
function buildLesenItems(data:LesenArchiveData):LesenExamItem[]{const t1:LesenExamItem[]=[];for(const task of data.teil1){for(let i=0;i<task.statements.length&&t1.length<5;i++){const s=task.statements[i];t1.push({id:`l1-${task.id}-${i}`,part:1,context:task.text,prompt:s.statement,options:[{value:'r',label:'Richtig'},{value:'f',label:'Falsch'}],correct:s.correct?'r':'f'})}if(t1.length>=5)break}const t2=data.teil2.slice(0,5).map((t,i)=>({id:`l2-${i}`,part:2 as const,context:t.situation,prompt:'Wo finden Sie die passende Information?',options:[{value:'a',label:`A · ${optionText(t.a)}`},{value:'b',label:`B · ${optionText(t.b)}`}],correct:t.correct}));const t3=data.teil3.slice(0,5).map((t,i)=>({id:`l3-${i}`,part:3 as const,context:[t.place,t.heading,...t.text].filter(Boolean).join('\n'),prompt:t.statement,options:[{value:'r',label:'Richtig'},{value:'f',label:'Falsch'}],correct:t.correct==='Richtig'?'r':'f'}));return[...t1,...t2,...t3]}
function optionText(o:LesenArchiveOption){return[o.url,o.title,...(o.lines??[]),...(o.rows??[]).flat()].filter(Boolean).join(' · ')}

function SchreibenMock({time,onBack,onExpire,onFinish}:{time:number;onBack:()=>void;onExpire:()=>void;onFinish:(r:RawResult)=>void}){const form=schreibenTeil1Tasks[0],letterTask=schreibenTeil2Tasks[0];const editable=form.rows.map((row,index)=>({row,index})).filter(x=>Boolean(x.row.answer));const[formValues,setFormValues]=useState<Record<number,string>>({});const[letter,setLetter]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const finish=async(timedOut=false)=>{setLoading(true);setError('');const formRaw=editable.reduce((s,x)=>s+(matches(formValues[x.index]||'',x.row.answer||'')?1:0),0);let letterRaw=0;if(letter.trim()){try{const r=await fetch('/api/check-schreiben',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:letter,situation:letterTask.situation,points:letterTask.points})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||'Письмо не удалось оценить');letterRaw=Math.max(0,Math.min(10,Number(p?.earned)||0))}catch(e){if(!timedOut){setError(e instanceof Error?e.message:'Не удалось оценить письмо');setLoading(false);return}}}setLoading(false);onFinish({raw:formRaw+letterRaw,rawMax:15})};return <Shell stage="schreiben" time={time} onBack={onBack} onExpire={onExpire} onFinish={finish} finishLoading={loading}><div className="space-y-5"><section className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-amber-700">Teil 1 · Formular</p><h2 className="mt-1 text-lg font-black">{form.title}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{form.scenario}</p><p className="mt-3 text-sm font-semibold">{form.instruction}</p><div className="mt-4 divide-y">{form.rows.map((row,index)=><div key={`${row.label}-${index}`} className="grid grid-cols-[minmax(95px,.8fr)_minmax(0,1.2fr)] items-center gap-3 py-3"><span className="text-sm font-semibold">{row.label}</span>{row.answer?<input value={formValues[index]||''} onChange={e=>setFormValues(v=>({...v,[index]:e.target.value}))} className="min-h-11 min-w-0 rounded-xl border px-3"/>:<span className="text-sm text-slate-600">{row.value}</span>}</div>)}</div></section><section className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-amber-700">Teil 2 · Brief</p><p className="mt-2 text-sm leading-7">{letterTask.situation}</p><ul className="mt-3 space-y-1 text-sm font-semibold">{letterTask.points.map(p=><li key={p}>• {p}</li>)}</ul><textarea value={letter} onChange={e=>setLetter(e.target.value)} className="mt-4 min-h-[230px] w-full rounded-xl border p-4 leading-7" placeholder="Schreiben Sie hier …"/><p className="mt-2 text-xs text-slate-400">Во время пробника Отто не показывает подсказки и исправления.</p></section>{error&&<p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}</div></Shell>}
function norm(v:string){return v.toLocaleLowerCase('de-DE').replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9@]+/g,' ').trim()}function matches(a:string,b:string){const x=norm(a),y=norm(b);return Boolean(x&&y&&(x===y||x.includes(y)||y.includes(x)))}

function SprechenMock({time,setIndex,onBack,onExpire,onFinish}:{time:number;setIndex:number;onBack:()=>void;onExpire:()=>void;onFinish:(r:RawResult)=>void}){const t2=useMemo(()=>{const start=(setIndex*2)%speakingTeil2Cards.length;return[speakingTeil2Cards[start],speakingTeil2Cards[(start+1)%speakingTeil2Cards.length]]},[setIndex]);const requestSets=useMemo(()=>Array.from({length:10},(_,n)=>[speakingTeil3ArchiveCards[(n*2)%speakingTeil3ArchiveCards.length],speakingTeil3ArchiveCards[(n*2+1)%speakingTeil3ArchiveCards.length]]),[]);const t3=requestSets[setIndex%10];const[scores,setScores]=useState<Record<string,number>>({});const finish=()=>{const t1Raw=(scores.t1??0)/100*3,t2Raw=((scores.t2a??0)+(scores.t2b??0))/100*3,t3Raw=((scores.t3a??0)+(scores.t3b??0))/100*3;onFinish({raw:Math.max(0,Math.min(15,t1Raw+t2Raw+t3Raw)),rawMax:15})};return <Shell stage="sprechen" time={time} onBack={onBack} onExpire={onExpire} onFinish={finish}><div className="mb-4 rounded-xl bg-teal-50 p-4 text-sm leading-6 text-teal-900">Ответы записываются и оцениваются, но баллы и обратная связь скрыты до итогового экрана. Для Teil 3 используется набор {setIndex+1} из 10.</div><section className="rounded-2xl border bg-white p-5"><b>Teil 1 · Sich vorstellen</b><p className="mt-2 text-sm text-slate-600">{speakingTeil1.checkPoints.join(' · ')}</p><ExamVoiceAnswer evaluation={{mode:'teil1',expectedPoints:speakingTeil1.checkPoints}} onScore={score=>setScores(v=>({...v,t1:score}))}/></section><section className="mt-4 rounded-2xl border bg-white p-5"><b>Teil 2 · Informationen geben und erfragen</b>{t2.map((card,i)=><div key={card.id} className="mt-4 rounded-xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-teal-700">Thema: {card.theme}</p><h3 className="mt-1 text-xl font-black">{card.keyword}</h3><p className="mt-2 text-sm text-slate-500">Задайте один понятный вопрос по теме и слову.</p><ExamVoiceAnswer evaluation={{mode:'teil2',theme:card.theme,keyword:card.keyword,sampleQuestion:card.sampleQuestion}} onScore={score=>setScores(v=>({...v,[i?'t2b':'t2a']:score}))}/></div>)}</section><section className="mt-4 rounded-2xl border bg-white p-5"><b>Teil 3 · Bitten formulieren und reagieren</b>{t3.map((card,i)=><div key={card.id} className="mt-4 rounded-xl border bg-[#fffefa] p-4"><p className="text-xs font-black uppercase text-amber-700">Karte {i+1}</p><Teil3ArchiveImage imageIndex={card.imageIndex} alt={card.alt} className="mx-auto mt-3 w-full max-w-xs rounded-xl"/><h3 className="mt-2 text-2xl font-black">{card.alt}</h3><p className="mt-2 text-sm text-slate-500">Сформулируйте просьбу и коротко отреагируйте на такую просьбу.</p><ExamVoiceAnswer evaluation={{mode:'teil3',object:card.alt,sampleRequest:card.sampleRequest}} onScore={score=>setScores(v=>({...v,[i?'t3b':'t3a']:score}))}/></div>)}</section></Shell>}

type VoiceEvaluation={mode:'teil1';expectedPoints:string[]}|{mode:'teil2';theme:string;keyword:string;sampleQuestion:string}|{mode:'teil3';object:string;sampleRequest:string};
function ExamVoiceAnswer({evaluation,onScore}:{evaluation:VoiceEvaluation;onScore:(score:number)=>void}){const[recording,setRecording]=useState(false);const[blob,setBlob]=useState<Blob|null>(null);const[url,setUrl]=useState('');const[checking,setChecking]=useState(false);const[saved,setSaved]=useState(false);const[error,setError]=useState('');const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const start=async()=>{setError('');setSaved(false);try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream);recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{const b=new Blob(chunks.current,{type:r.mimeType||'audio/webm'});stream.getTracks().forEach(t=>t.stop());setBlob(b);if(url)URL.revokeObjectURL(url);setUrl(URL.createObjectURL(b));setRecording(false)};r.start(250);setRecording(true)}catch{setError('Не удалось включить микрофон. Разрешите доступ и попробуйте ещё раз.')}};const stop=()=>{if(recorder.current?.state==='recording')recorder.current.stop()};const check=async()=>{if(!blob)return;setChecking(true);setError('');try{const audioBase64=await blobToBase64(blob);const r=await fetch('/api/check-sprechen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...evaluation,audioBase64,mimeType:blob.type||'audio/webm'})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||'Не удалось оценить запись');onScore(Math.max(0,Math.min(100,Number(p?.score)||0)));setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Не удалось оценить запись')}finally{setChecking(false)}};return <div className="mt-3 rounded-xl border bg-white p-3">{!blob&&!recording&&<button type="button" onClick={start} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-rose-600 px-4 font-bold text-white"><Mic className="h-4 w-4"/>Записать ответ</button>}{recording&&<button type="button" onClick={stop} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 font-bold text-white"><Square className="h-4 w-4"/>Остановить</button>}{blob&&<><audio src={url} controls className="w-full"/><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setBlob(null);setSaved(false)}} className="min-h-10 rounded-xl border px-3 font-bold">Перезаписать</button><button type="button" onClick={check} disabled={checking||saved} className="min-h-10 rounded-xl bg-teal-700 px-3 font-bold text-white disabled:opacity-50">{checking?'Проверяется…':saved?'Ответ сохранён':'Сохранить ответ'}</button></div></>}{error&&<p className="mt-2 text-xs text-rose-700">{error}</p>}{saved&&<p className="mt-2 text-xs font-semibold text-emerald-700">✓ Ответ принят. Оценка будет только в итоговом результате.</p>}</div>}
function blobToBase64(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||'').split(',')[1]||'');reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}

function FinalResult({attempt,onBack,onRestart}:{attempt:MockAttempt;onBack:()=>void;onRestart:()=>void}){const sorted=(Object.entries(attempt.sections) as Array<[ModuleId,{points:number}]>).sort((a,b)=>a[1].points-b[1].points);const recommendations=sorted.slice(0,sorted[0][1].points<18?3:2).map(([id])=>recommendation(id));return <div className="animate-fade-in pb-8"><Header onBack={onBack}/><section className={cn('rounded-3xl p-6 text-white',attempt.passed?'bg-teal-800':'bg-slate-900')}><Trophy className="h-11 w-11 text-amber-300"/><p className="mt-3 text-sm font-bold uppercase tracking-wider text-white/65">Итог пробного экзамена</p><h2 className="mt-1 text-5xl font-black">{attempt.total}/100</h2><p className="mt-2 text-xl font-black">{attempt.passed?'Экзаменационный порог пройден':'Пока ниже проходного порога'}</p><p className="mt-1 text-sm text-white/70">Оценка: {attempt.grade}. Проходной порог Goethe A1 — 60/100 при выполнении всех частей.</p></section><section className="mt-5 grid gap-3 sm:grid-cols-2">{(['horen','lesen','schreiben','sprechen'] as ModuleId[]).map(id=><div key={id} className="rounded-2xl border bg-white p-4"><p className="text-xs font-black uppercase text-slate-400">{SECTION_LABEL[id as SectionStage]}</p><strong className="mt-1 block text-3xl">{attempt.sections[id].points}/25</strong><p className="mt-1 text-xs text-slate-500">Результат до пересчёта: {round1(attempt.sections[id].raw)}/{attempt.sections[id].rawMax}</p></div>)}</section><section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-black text-amber-950">Что потренировать дальше</h3><div className="mt-3 space-y-2">{recommendations.map((text,i)=><p key={i} className="rounded-xl bg-white px-3 py-2 text-sm leading-6 text-slate-700">{i+1}. {text}</p>)}</div></section><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={onRestart} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border bg-white px-5 font-bold"><RotateCcw className="h-4 w-4"/>Новый пробный экзамен</button><button onClick={onBack} className="min-h-11 rounded-xl bg-slate-900 px-5 font-bold text-white">Вернуться к тренировкам</button></div></div>}
function recommendation(id:ModuleId){if(id==='horen')return'Сделайте несколько коротких Hören-серий и разберите, где теряются числа, время или ключевые слова.';if(id==='lesen')return'Пройдите по 5–10 заданий Lesen из каждого Teil и обязательно разберите ошибки.';if(id==='schreiben')return'Повторите Formular и одно письмо: обращение → три пункта → прощание.';return'Запишите ответы Sprechen Teil 1–3 ещё раз и доведите их до понятной, устойчивой речи.'}
function Header({onBack}:{onBack:()=>void}){return <div className="mb-5 flex items-center gap-3"><button onClick={onBack} className="flex h-11 w-11 items-center justify-center rounded-xl border bg-white"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-black">Пробный экзамен</h1><p className="text-sm text-slate-500">Goethe-Zertifikat A1 · экзаменационный режим</p></div></div>}
function examChoice(selected:boolean){return cn('min-h-11 rounded-xl border-2 px-3 py-2 text-left',selected?'border-sky-500 bg-sky-50':'border-slate-200 bg-white')}
function fmt(sec:number){return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function round1(v:number){return Math.round(v*10)/10}
