import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock, Mic, Play, RotateCcw, Square, Trophy } from 'lucide-react';
import { listeningTasks } from '@/data/listening';
import { loadLesenArchive, type LesenArchiveData, type LesenArchiveOption } from '@/data/lesen/archiveData';
import { schreibenTeil1Tasks } from '@/data/schreiben/teil1';
import { schreibenTeil2Tasks } from '@/data/schreiben/teil2';
import { speakingTeil1, speakingTeil2Cards } from '@/data/speaking';
import { speakingTeil3ArchiveCards } from '@/data/speakingTeil3Archive';
import type { ModuleId } from '@/types';
import { cn } from '@/lib/utils';

type Stage='menu'|'horen'|'lesen'|'schreiben'|'sprechen'|'result';
type ExamModule='horen'|'lesen'|'schreiben'|'sprechen';
type Scores=Partial<Record<ExamModule,number>>;
interface Props{onBack:()=>void;onModuleComplete?:(module:ModuleId,score:number,total:number)=>void}
const DURATIONS:Record<ExamModule,number>={horen:20*60,lesen:25*60,schreiben:20*60,sprechen:15*60};
const MODULE_MAX=15;
const CURRENT_KEY='otto-a1-mock-current-v2';
const HISTORY_KEY='otto-a1-mock-history-v2';

interface CurrentAttempt {id:string;form:Record<number,string>;letter:string;variant:number}
function readAttempt():CurrentAttempt{
 try{const raw=JSON.parse(localStorage.getItem(CURRENT_KEY)||'{}');return {id:String(raw.id||`mock-${Date.now()}`),form:raw.form&&typeof raw.form==='object'?raw.form:{},letter:String(raw.letter||''),variant:Number.isInteger(raw.variant)?Math.max(0,Math.min(9,raw.variant)):Math.floor(Math.random()*10)}}catch{return{id:`mock-${Date.now()}`,form:{},letter:'',variant:Math.floor(Math.random()*10)}}
}
function saveAttempt(value:CurrentAttempt){try{localStorage.setItem(CURRENT_KEY,JSON.stringify(value))}catch{}}
function norm(value:string){return value.toLocaleLowerCase('de-DE').replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim()}

export function MockExam({onBack,onModuleComplete}:Props){
 const[stage,setStage]=useState<Stage>('menu'),[time,setTime]=useState(0),[done,setDone]=useState<ExamModule[]>([]),[scores,setScores]=useState<Scores>({}),[finalized,setFinalized]=useState(false);
 const[lesenData,setLesenData]=useState<LesenArchiveData|null>(null);
 const[horenAnswers,setHorenAnswers]=useState<Record<number,number|boolean>>({});
 const[lesenAnswers,setLesenAnswers]=useState<Record<number,string|boolean>>({});
 const[current,setCurrent]=useState<CurrentAttempt>(readAttempt);
 const[form,setForm]=useState<Record<number,string>>(current.form),[letter,setLetter]=useState(current.letter),[writingChecking,setWritingChecking]=useState(false);
 const[sprechScores,setSprechScores]=useState<Partial<Record<1|2|3,number>>>({});
 useEffect(()=>{loadLesenArchive().then(setLesenData).catch(()=>setLesenData(null))},[]);
 useEffect(()=>{const next={...current,form,letter};saveAttempt(next)},[current,form,letter]);
 useEffect(()=>{if(!['horen','lesen','schreiben','sprechen'].includes(stage)||time<=0)return;const id=window.setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>window.clearInterval(id)},[stage,time]);
 const start=(s:ExamModule)=>{setStage(s);setTime(DURATIONS[s]);window.scrollTo({top:0,behavior:'smooth'})};
 const markDone=(module:ExamModule,raw:number)=>{setScores(prev=>({...prev,[module]:Math.max(0,Math.min(MODULE_MAX,raw))}));setDone(prev=>prev.includes(module)?prev:[...prev,module]);setStage('menu');window.scrollTo({top:0,behavior:'smooth'})};
 const finishSimple=(module:'horen'|'lesen')=>{
   if(module==='horen'){
     const raw=listeningTasks.slice(0,15).reduce((n,t,i)=>{
       const a=horenAnswers[i];
       return n+(t.type==='multiple-choice'?(a===t.correctIndex?1:0):(a===t.correctAnswer?1:0));
     },0);
     markDone('horen',raw);return;
   }
   const qs=lesenData?buildLesenQuestions(lesenData):[];const raw=qs.reduce((n,q,i)=>n+(lesenAnswers[i]===q.correct?1:0),0);markDone('lesen',raw);
 };
 const finishWriting=async()=>{
   const task=schreibenTeil1Tasks[0];const editable=task.rows.map((row,i)=>({row,i})).filter(x=>Boolean(x.row.answer));
   if(editable.some(({i})=>!String(form[i]||'').trim())||!letter.trim())return;
   setWritingChecking(true);
   const formScore=editable.reduce((sum,{row,i})=>sum+(norm(form[i]||'')===norm(row.answer||'')?1:0),0);
   let letterScore=0;
   try{const brief=schreibenTeil2Tasks[0];const r=await fetch('/api/check-schreiben',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:letter,situation:brief.situation,points:brief.points})});const p=await r.json().catch(()=>({}));if(r.ok)letterScore=Math.max(0,Math.min(10,Number(p.earned)||0))}catch{/* score stays 0 */}finally{setWritingChecking(false)}
   markDone('schreiben',formScore+letterScore);
 };
 const finishSpeaking=()=>{if(sprechScores[1]===undefined||sprechScores[2]===undefined||sprechScores[3]===undefined)return;const raw=(sprechScores[1]??0)*3/100+(sprechScores[2]??0)*6/100+(sprechScores[3]??0)*6/100;markDone('sprechen',raw)};
 const showResult=()=>{
   setStage('result');
   if(finalized)return;
   setFinalized(true);
   const entry={id:current.id,at:new Date().toISOString(),scores};
   let fresh=true;
   try{
     const history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');
     const list=Array.isArray(history)?history:[];
     fresh=!list.some((x:{id?:string})=>x?.id===current.id);
     if(fresh)localStorage.setItem(HISTORY_KEY,JSON.stringify([entry,...list].slice(0,20)));
   }catch{/* keep current-session guard */}
   if(fresh)(Object.entries(scores) as [ExamModule,number][]).forEach(([module,raw])=>onModuleComplete?.(module,raw,MODULE_MAX));
 };
 const resetExam=()=>{const fresh:CurrentAttempt={id:`mock-${Date.now()}`,form:{},letter:'',variant:Math.floor(Math.random()*10)};setCurrent(fresh);saveAttempt(fresh);setForm({});setLetter('');setHorenAnswers({});setLesenAnswers({});setSprechScores({});setScores({});setDone([]);setFinalized(false);setStage('menu')};
 const formComplete=schreibenTeil1Tasks[0].rows.map((row,i)=>({row,i})).filter(({row})=>Boolean(row.answer)).every(({i})=>Boolean(String(form[i]||'').trim()));

 if(stage==='menu')return <div className="animate-fade-in pb-8"><Header onBack={onBack}/><div className="rounded-3xl border border-slate-800 bg-slate-950 p-6 text-white"><Trophy className="h-10 w-10 text-amber-300"/><h2 className="mt-3 text-2xl font-black">Пробный экзамен A1</h2><p className="mt-2 text-sm leading-6 text-white/80">Структура сверена с актуальным Goethe-Zertifikat A1: Start Deutsch 1: Hören — 3 Teil / 15 заданий, Lesen — 3 Teil / 15 заданий, Schreiben — Formular + короткое письмо, Sprechen — 3 Teil. Итог показывается только после всех четырёх частей.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{([['horen','Hören','20 минут'],['lesen','Lesen','25 минут'],['schreiben','Schreiben','20 минут'],['sprechen','Sprechen','15 минут']] as const).map(([id,title,d])=><button key={id} onClick={()=>start(id)} className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm"><div className="flex items-center justify-between"><b className="text-lg text-slate-950">{title}</b>{done.includes(id)&&<CheckCircle2 className="h-5 w-5 text-emerald-600"/>}</div><p className="mt-1 text-sm text-slate-500">{d}</p><span className="mt-4 inline-block font-bold text-teal-700">{done.includes(id)?'Пройти ещё раз':'Начать'} →</span></button>)}</div>{done.length===4&&<button onClick={showResult} className="mt-5 min-h-12 w-full rounded-xl bg-slate-950 font-bold text-white">Показать итоговый результат</button>}</div>;

 if(stage==='result')return <ResultScreen scores={scores} onBack={onBack} onRetry={resetExam}/>;
 const module=stage as ExamModule;
 const canFinish=module==='horen'?Object.keys(horenAnswers).length===15:module==='lesen'?Boolean(lesenData)&&Object.keys(lesenAnswers).length===15:module==='schreiben'?formComplete&&Boolean(letter.trim()):Boolean(sprechScores[1]!==undefined&&sprechScores[2]!==undefined&&sprechScores[3]!==undefined);
 return <ExamShell stage={module} time={time} onBack={()=>setStage('menu')} canFinish={canFinish} onFinish={()=>module==='horen'||module==='lesen'?finishSimple(module):module==='schreiben'?void finishWriting():finishSpeaking()} busy={writingChecking}>
   {module==='horen'&&<HorenExam answers={horenAnswers} onAnswer={(i,v)=>setHorenAnswers(prev=>({...prev,[i]:v}))}/>} 
   {module==='lesen'&&<LesenExam data={lesenData} answers={lesenAnswers} onAnswer={(i,v)=>setLesenAnswers(prev=>({...prev,[i]:v}))}/>} 
   {module==='schreiben'&&<SchreibenExam form={form} setForm={setForm} letter={letter} setLetter={setLetter}/>} 
   {module==='sprechen'&&<SprechenExam variant={current.variant} scores={sprechScores} onScore={(part,score)=>setSprechScores(prev=>({...prev,[part]:score}))}/>} 
 </ExamShell>;
}

function ExamShell({stage,time,onBack,onFinish,canFinish,busy,children}:{stage:ExamModule;time:number;onBack:()=>void;onFinish:()=>void;canFinish:boolean;busy:boolean;children:React.ReactNode}){return <div className="animate-fade-in pb-8"><div className="sticky top-0 z-30 -mx-4 mb-5 flex items-center justify-between gap-3 border-b border-slate-200 bg-[#f7f4ee]/95 px-4 py-3 backdrop-blur"><button onClick={onBack} className="flex h-10 w-10 items-center justify-center rounded-xl border bg-white"><ArrowLeft className="h-5 w-5"/></button><b className="text-lg">{stageTitle(stage)}</b><span className={cn('inline-flex items-center gap-2 rounded-xl px-3 py-2 font-mono font-bold',time<60?'bg-rose-100 text-rose-700':'bg-slate-900 text-white')}><Clock className="h-4 w-4"/>{fmt(time)}</span></div>{children}<button onClick={onFinish} disabled={!canFinish||busy} className="mt-6 min-h-12 w-full rounded-xl bg-slate-900 px-5 font-bold text-white disabled:opacity-40">{busy?'Проверка сохраняется…':'Завершить часть'}</button>{time===0&&<p className="mt-2 text-center text-sm font-bold text-rose-700">Время закончилось. Завершите часть, когда ответы сохранены.</p>}<p className="mt-2 text-center text-xs text-slate-500">Баллы и разбор будут показаны только после завершения всего пробного экзамена.</p></div>}

function HorenExam({answers,onAnswer}:{answers:Record<number,number|boolean>;onAnswer:(i:number,v:number|boolean)=>void}){const items=listeningTasks.slice(0,15);return <div><div className="mb-4 rounded-xl border border-sky-100 bg-sky-50 p-4 text-sm leading-6 text-sky-950"><b>Hören · 15 заданий</b><br/>Teil 1: 1–6, два прослушивания. Teil 2: 7–10, одно прослушивание. Teil 3: 11–15, два прослушивания. Используются готовые экзаменационные аудиозаписи, а не голос Отто.</div><div className="space-y-4">{items.map((t,i)=><AudioQuestion key={t.id} task={t} value={answers[i]} onChange={v=>onAnswer(i,v)} limit={i<6?2:i<10?1:2} part={i<6?1:i<10?2:3}/>)}</div></div>}
function AudioQuestion({task,value,onChange,limit,part}:{task:any;value:number|boolean|undefined;onChange:(v:number|boolean)=>void;limit:number;part:number}){const[plays,setPlays]=useState(0),audioRef=useRef<HTMLAudioElement|null>(null);const play=()=>{if(plays>=limit)return;const a=audioRef.current;if(!a)return;a.currentTime=0;void a.play();setPlays(v=>v+1)};return <div className="rounded-2xl border bg-white p-4"><div className="flex items-center justify-between gap-2"><span className="text-xs font-black uppercase text-sky-700">Teil {part} · Aufgabe {task.number}</span><span className="text-xs text-slate-500">{plays}/{limit}</span></div><audio ref={audioRef} src={`/audio/${String(task.number).padStart(3,'0')}.mp3`} preload="metadata"/><button type="button" disabled={plays>=limit} onClick={play} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-xl bg-sky-50 px-3 text-sm font-bold text-sky-900 disabled:opacity-40"><Play className="h-4 w-4"/>Слушать</button><p className="mt-3 font-semibold">{task.prompt}</p><div className="mt-3 grid gap-2">{task.type==='multiple-choice'?task.options.map((o:string,n:number)=><button key={`${o}-${n}`} onClick={()=>onChange(n)} className={examChoice(value===n)}>{String.fromCharCode(65+n)}. {o}</button>):[true,false].map(v=><button key={String(v)} onClick={()=>onChange(v)} className={examChoice(value===v)}>{v?'Richtig':'Falsch'}</button>)}</div></div>}

interface LesenQuestion{part:1|2|3;label:string;text:string;question:string;options:Array<{value:string|boolean;label:string}>;correct:string|boolean}
function optionText(option:LesenArchiveOption){return [option.url,option.title,...(option.lines??[]),...(option.rows??[]).flat()].filter(Boolean).join(' · ')}
function buildLesenQuestions(data:LesenArchiveData):LesenQuestion[]{
 const t1:LesenQuestion[]=[];for(const task of data.teil1){for(const s of task.statements){t1.push({part:1,label:'Richtig oder Falsch',text:task.text,question:s.statement,options:[{value:true,label:'Richtig'},{value:false,label:'Falsch'}],correct:s.correct});if(t1.length===5)break}if(t1.length===5)break}
 const t2=data.teil2.slice(0,5).map<LesenQuestion>(task=>({part:2,label:'Wo finden Sie Informationen?',text:task.situation,question:task.situation,options:[{value:'a',label:`A · ${optionText(task.a)}`},{value:'b',label:`B · ${optionText(task.b)}`}],correct:task.correct}));
 const t3=data.teil3.slice(0,5).map<LesenQuestion>(task=>({part:3,label:task.place,text:[task.heading,...task.text].filter(Boolean).join('\n'),question:task.statement,options:[{value:true,label:'Richtig'},{value:false,label:'Falsch'}],correct:task.correct==='Richtig'}));
 return [...t1,...t2,...t3];
}
function LesenExam({data,answers,onAnswer}:{data:LesenArchiveData|null;answers:Record<number,string|boolean>;onAnswer:(i:number,v:string|boolean)=>void}){if(!data)return <div className="rounded-2xl border bg-white p-6 text-center text-slate-500">Загружаю Lesen…</div>;const qs=buildLesenQuestions(data);return <div className="space-y-4"><div className="rounded-xl border border-teal-100 bg-teal-50 p-4 text-sm leading-6 text-teal-950">Lesen: 3 Teil, по 5 заданий. Во время экзамена переводов и обучающих подсказок нет.</div>{qs.map((q,i)=><div key={i} className="rounded-2xl border bg-white p-4"><p className="text-xs font-black uppercase text-teal-700">Teil {q.part} · Aufgabe {i+1}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{q.text}</p><p className="mt-4 font-semibold leading-6">{q.question}</p><div className="mt-3 grid gap-2">{q.options.map((o,n)=><button key={n} onClick={()=>onAnswer(i,o.value)} className={examChoice(answers[i]===o.value)}>{o.label}</button>)}</div></div>)}</div>}

function SchreibenExam({form,setForm,letter,setLetter}:{form:Record<number,string>;setForm:React.Dispatch<React.SetStateAction<Record<number,string>>>;letter:string;setLetter:(v:string)=>void}){const task=schreibenTeil1Tasks[0],brief=schreibenTeil2Tasks[0];return <div className="space-y-4"><div className="rounded-xl border border-amber-100 bg-amber-50 p-4 text-sm leading-6 text-amber-950">Schreiben: Teil 1 Formular — 5 Punkte. Teil 2 короткое письмо — 10 Punkte. Проверка и исправления появятся только в общем итоге.</div><section className="rounded-2xl border bg-white p-5"><b>Teil 1 · Formular</b><p className="mt-2 text-sm leading-6 text-slate-700">{task.scenario}</p><div className="mt-4 space-y-3">{task.rows.map((row,i)=><div key={`${row.label}-${i}`} className="grid gap-2 sm:grid-cols-[180px_1fr]"><label className="text-sm font-bold text-slate-700">{row.label}</label>{row.answer?<input value={form[i]||''} onChange={e=>setForm(prev=>({...prev,[i]:e.target.value}))} className="min-h-11 rounded-xl border px-3"/>:<div className="rounded-xl bg-slate-50 px-3 py-2 text-sm">{row.value}</div>}</div>)}</div></section><section className="rounded-2xl border bg-white p-5"><b>Teil 2 · Brief</b><p className="mt-2 text-sm leading-6 text-slate-700">{brief.situation}</p><ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{brief.points.map(p=><li key={p}>{p}</li>)}</ul><textarea value={letter} onChange={e=>setLetter(e.target.value)} className="mt-4 min-h-[220px] w-full rounded-xl border p-4" placeholder="Schreiben Sie hier …"/></section></div>}

function SprechenExam({variant,scores,onScore}:{variant:number;scores:Partial<Record<1|2|3,number>>;onScore:(part:1|2|3,score:number)=>void}){const t2=speakingTeil2Cards[variant%speakingTeil2Cards.length];const t3=speakingTeil3ArchiveCards[(variant*5)%speakingTeil3ArchiveCards.length];return <div className="space-y-4"><div className="rounded-xl border border-violet-100 bg-violet-50 p-4 text-sm leading-6 text-violet-950">Sprechen: Teil 1 — максимум 3 балла; Teil 2 — 6; Teil 3 — 6. Вариант карточек {variant+1} из 10. Оценка каждой записи скрыта до общего итога.</div><section className="rounded-2xl border bg-white p-5"><b>Teil 1 · Sich vorstellen</b><p className="mt-2 text-sm">Name · Alter · Land · Wohnort · Sprachen · Beruf · Hobby</p><ExamVoice part={1} evaluation={{mode:'teil1',expectedPoints:speakingTeil1.checkPoints}} saved={scores[1]!==undefined} onScore={score=>onScore(1,score)}/></section><section className="rounded-2xl border bg-white p-5"><b>Teil 2 · Um Informationen bitten</b><p className="mt-2 text-xs font-black uppercase text-slate-400">Thema: {t2.theme}</p><div className="mt-2 rounded-xl border bg-slate-50 p-4 text-center text-2xl font-black">{t2.keyword}</div><ExamVoice part={2} evaluation={{mode:'teil2',theme:t2.theme,keyword:t2.keyword,sampleQuestion:t2.sampleQuestion}} saved={scores[2]!==undefined} onScore={score=>onScore(2,score)}/></section><section className="rounded-2xl border bg-white p-5"><b>Teil 3 · Bitte formulieren und reagieren</b><p className="mt-2 text-xs text-slate-500">Karte</p><div className="mt-2 rounded-xl border bg-slate-50 p-5 text-center text-2xl font-black">{t3.alt}</div><p className="mt-2 text-xs leading-5 text-slate-500">Новые изображения Teil 3 не подменяются старыми: в этом Preview экзаменационная карточка использует только проверенное название предмета до получения нового архива изображений.</p><ExamVoice part={3} evaluation={{mode:'teil3',object:t3.alt,sampleRequest:t3.sampleRequest}} saved={scores[3]!==undefined} onScore={score=>onScore(3,score)}/></section></div>}

function ExamVoice({part,evaluation,saved,onScore}:{part:1|2|3;evaluation:Record<string,unknown>;saved:boolean;onScore:(score:number)=>void}){const[recording,setRecording]=useState(false),[blob,setBlob]=useState<Blob|null>(null),[checking,setChecking]=useState(false),[error,setError]=useState('');const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);const start=async()=>{setError('');setBlob(null);try{const s=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(s);recorder.current=r;chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{setBlob(new Blob(chunks.current,{type:r.mimeType||'audio/webm'}));s.getTracks().forEach(t=>t.stop());setRecording(false)};r.start();setRecording(true)}catch{setError('Не удалось включить микрофон. Проверьте разрешение браузера.')}};const stop=()=>recorder.current?.state==='recording'&&recorder.current.stop();const submit=async()=>{if(!blob||checking)return;setChecking(true);setError('');try{const audioBase64=await blobBase64(blob);const r=await fetch('/api/check-sprechen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...evaluation,audioBase64,mimeType:blob.type||'audio/webm'})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'Проверка недоступна');onScore(Math.max(0,Math.min(100,Number(p.score)||0)))}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить ответ.')}finally{setChecking(false)}};return <div className="mt-4 rounded-xl bg-slate-50 p-4">{saved?<div className="flex items-center gap-2 font-bold text-emerald-700"><CheckCircle2 className="h-5 w-5"/>Ответ Teil {part} сохранён. Балл скрыт до общего результата.</div>:<>{!recording&&!blob&&<button type="button" onClick={start} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-rose-600 px-4 font-bold text-white"><Mic className="h-4 w-4"/>Записать ответ</button>}{recording&&<button type="button" onClick={stop} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 font-bold text-white"><Square className="h-4 w-4"/>Остановить</button>}{blob&&!recording&&<div className="space-y-3"><audio src={URL.createObjectURL(blob)} controls className="w-full"/><button type="button" disabled={checking} onClick={submit} className="min-h-11 w-full rounded-xl bg-slate-900 px-4 font-bold text-white disabled:opacity-40">{checking?'Сохраняю оценку…':'Сохранить ответ'}</button></div>}{error&&<p className="mt-2 text-sm text-rose-700">{error}</p>}</>}</div>}
function blobBase64(blob:Blob){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||'').split(',')[1]||'');r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}

function ResultScreen({scores,onBack,onRetry}:{scores:Scores;onBack:()=>void;onRetry:()=>void}){const modules:ExamModule[]=['horen','lesen','schreiben','sprechen'];const points=Object.fromEntries(modules.map(id=>[id,(scores[id]??0)*25/15])) as Record<ExamModule,number>;const total=Math.round(modules.reduce((s,id)=>s+points[id],0));const weakest=modules.reduce((a,b)=>points[b]<points[a]?b:a);const errors=Object.fromEntries(modules.map(id=>[id,Math.max(0,Math.round(15-(scores[id]??0)))])) as Record<ExamModule,number>;const label=(p:number)=>p>=20?'уверенно':p>=16?'хорошо':p>=12?'нужно закрепить':'нужно подтянуть';return <div className="animate-fade-in pb-8"><Header onBack={onBack}/><section className="rounded-3xl bg-slate-950 p-6 text-white"><Trophy className="h-10 w-10 text-amber-300"/><p className="mt-3 text-sm font-bold text-white/60">Итоговый результат</p><strong className="mt-1 block text-5xl font-black">{total}/100</strong><p className="mt-2 text-sm text-white/80">{total>=60?'Экзаменационный порог тренировки достигнут.':'Сейчас полезнее укрепить слабые места и повторить пробник.'}</p></section><div className="mt-5 grid gap-3 sm:grid-cols-2">{modules.map(id=><div key={id} className="rounded-2xl border bg-white p-4"><div className="flex items-center justify-between"><strong>{stageTitle(id)}</strong><b>{Math.round(points[id])}/25</b></div><p className="mt-1 text-sm text-slate-600">{label(points[id])} · ошибок/потерь: {errors[id]}</p></div>)}</div><section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-lg font-black">Что делать дальше</h2><p className="mt-2 text-sm leading-6">Больше всего внимания сейчас требует <b>{stageTitle(weakest)}</b>.</p><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-6"><li>сделать короткую тренировку {stageTitle(weakest)};</li><li>разобрать ошибки из этого раздела;</li><li>{weakest==='horen'?'повторить числа, время и ключевые детали на слух':weakest==='sprechen'?'выполнить 5 голосовых карточек Teil 2/3':'выполнить 10–15 заданий слабого типа'};</li><li>затем повторить пробный экзамен.</li></ol></section><button onClick={onRetry} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border bg-white px-5 font-bold"><RotateCcw className="h-4 w-4"/>Новый вариант пробного экзамена</button></div>}

function Header({onBack}:{onBack:()=>void}){return <div className="mb-5 flex items-center gap-3"><button onClick={onBack} className="flex h-11 w-11 items-center justify-center rounded-xl border bg-white"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-black">Пробный экзамен</h1><p className="text-sm text-slate-500">Goethe-Zertifikat A1 · экзаменационный режим</p></div></div>}
function examChoice(active:boolean){return cn('min-h-11 rounded-xl border-2 px-3 py-2 text-left',active?'border-teal-600 bg-teal-50':'border-slate-200 bg-white')}
function stageTitle(s:string){return s==='horen'?'Hören':s==='lesen'?'Lesen':s==='schreiben'?'Schreiben':'Sprechen'}
function fmt(sec:number){return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
