import { ArrowLeft,ArrowRight,Brain,CheckCircle2,CircleAlert,Clock3,Quote,Target,Trophy } from 'lucide-react';
import type { ActivityEntry,ModuleId,Progress } from '@/types';
import { loadLearningProfile } from '@/lib/learningProfile';
import { getReadiness,getTodayActivity,MODULE_META,MODULE_ORDER } from '@/lib/preparation';
import { useUiLanguage } from '@/lib/i18n';
interface Props{progress:Progress;activity:ActivityEntry[];onBack:()=>void;onSelectModule:(m:ModuleId)=>void;onOpenMockExam:()=>void;onOpenPhrases:()=>void}
const dot={ready:'bg-emerald-500',almost:'bg-amber-400',train:'bg-rose-500'} as const;
export function ReadinessPage({progress,activity,onBack,onSelectModule,onOpenMockExam,onOpenPhrases}:Props){
 const{lang,t}=useUiLanguage();const r=getReadiness(progress,activity),today=getTodayActivity(activity),learning=loadLearningProfile(),week=activity.filter(e=>Date.now()-new Date(e.at).getTime()<=7*86400000),weekMinutes=Math.round(week.reduce((s,e)=>s+(e.durationSeconds??0),0)/60),weak=r.modules[r.weakest],topError=learning.errors[0];
 return <div className="otto-readiness-screen animate-fade-in pb-8">
  <div className="mb-4 flex items-center gap-3"><button type="button" onClick={onBack} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border bg-white" aria-label={t('back')}><ArrowLeft className="h-5 w-5"/></button><div><p className="text-xs font-black uppercase tracking-[.14em] text-teal-700">{lang==='de'?'Mein Weg zu A1':'Мой путь к A1'}</p><h1 className="text-2xl font-black text-slate-950">{lang==='de'?'Prüfungsbereitschaft':'Готовность к экзамену'}</h1></div></div>
  <section className="rounded-[28px] bg-slate-950 p-5 text-white shadow-[0_20px_50px_rgba(15,23,42,.15)] sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-white/65">{lang==='de'?'Evidenzbasierte Trainingsbewertung':'Оценка по вашим результатам'}</p><strong className="mt-1 block text-5xl font-black">{r.overall===null?'—':`${r.overall}%`}</strong></div><Target className="h-9 w-9 text-teal-300"/></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-teal-400" style={{width:`${r.overall??0}%`}}/></div><p className="mt-3 text-sm leading-6 text-white/70">{r.evidenceLabel}. {lang==='de'?'Eine einzelne gute Antwort erzeugt keine hohe Bereitschaft.':'Одной удачной попытки недостаточно для высокой оценки готовности.'}</p></section>
  <section className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl border bg-white p-4"><Clock3 className="h-5 w-5 text-teal-700"/><strong className="mt-2 block text-2xl">{today.minutes} {t('minutes')}</strong><span className="text-xs text-slate-500">{lang==='de'?'heute aktiv':'активной практики сегодня'}</span></div><div className="rounded-2xl border bg-white p-4"><CheckCircle2 className="h-5 w-5 text-emerald-600"/><strong className="mt-2 block text-2xl">{today.attempts}</strong><span className="text-xs text-slate-500">{lang==='de'?'Versuche heute':'за сегодня'}</span></div></section>
  <section className="mt-6"><h2 className="text-xl font-black">{lang==='de'?'Bereitschaftskarte':'Карта готовности'}</h2><div className="mt-3 space-y-3">{MODULE_ORDER.map(id=>{const m=r.modules[id];return <button key={id} type="button" onClick={()=>onSelectModule(id)} className="w-full rounded-2xl border bg-white p-4 text-left shadow-sm"><div className="flex items-center gap-3"><span className={`h-3 w-3 shrink-0 rounded-full ${dot[m.status]}`}/><span className="min-w-0 flex-1"><strong className="block">{MODULE_META[id].title}</strong><small className="text-slate-500">{m.dataSufficient?m.note:t('insufficient')}</small></span><b className="text-xl">{m.dataSufficient?`${m.score}%`:'—'}</b><ArrowRight className="h-4 w-4 text-slate-300"/></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600" style={{width:`${m.dataSufficient?m.score:0}%`}}/></div><p className="mt-2 text-xs leading-5 text-slate-500">{m.evidence}</p></button>})}</div></section>
  <section className="mt-6 rounded-[24px] border border-amber-200 bg-amber-50 p-4 sm:p-5"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-700"/><div><p className="text-xs font-black uppercase tracking-[.13em] text-amber-800">{lang==='de'?'Was jetzt am wichtigsten ist':'Что сейчас важнее всего'}</p><h2 className="mt-1 text-lg font-black">{MODULE_META[r.weakest].title} {weak.dataSufficient?`— ${weak.score}%`:''}</h2><p className="mt-1 text-sm leading-6 text-slate-700">{!r.dataSufficient?r.recommendation:`Сейчас этому навыку стоит уделить больше внимания.${topError?` В письмах повторяется: ${topError.tag} (${topError.count}).`:''}`}</p></div></div><button type="button" onClick={()=>onSelectModule(r.weakest)} className="mt-4 min-h-11 w-full rounded-xl bg-amber-900 px-4 font-black text-white">{lang==='de'?'Diesen Bereich trainieren':'Потренировать слабое место'}</button></section>
  <section className="mt-6 rounded-[24px] border bg-white p-4 sm:p-5"><div className="flex items-center gap-2"><Brain className="h-5 w-5 text-amber-700"/><h2 className="text-lg font-black">{lang==='de'?'Meine Fehler':'Мои ошибки'}</h2></div>{learning.errors.length?<div className="mt-3 space-y-2">{learning.errors.slice(0,5).map(e=><div key={e.tag} className="rounded-xl bg-amber-50 px-3 py-3"><div className="flex justify-between gap-3"><strong className="text-sm">{e.tag}</strong><span className="rounded-full bg-white px-2 py-1 text-xs font-black">{e.count}</span></div>{e.examples[0]&&<p className="mt-1 text-xs"><span className="line-through">{e.examples[0].original}</span> → <span className="font-semibold text-emerald-700">{e.examples[0].corrected}</span></p>}</div>)}</div>:<p className="mt-2 text-sm text-slate-500">{t('insufficient')}</p>}</section>
  <section className="mt-6 rounded-[24px] border border-teal-100 bg-teal-50/60 p-4 sm:p-5"><div className="flex items-center gap-2"><Quote className="h-5 w-5 text-teal-700"/><h2 className="text-lg font-black">{lang==='de'?'Meine Sätze':'Мои фразы'}</h2></div>{learning.phrases.length?<><div className="mt-3 flex flex-wrap gap-2">{learning.phrases.slice(0,8).map(p=><span key={p.text} className="rounded-xl bg-white px-3 py-2 text-sm font-semibold shadow-sm">{p.text}</span>)}</div><button type="button" onClick={onOpenPhrases} className="mt-4 min-h-11 w-full rounded-xl bg-teal-800 px-4 font-black text-white">{lang==='de'?'Sätze laut sprechen':'Сказать мои фразы вслух'}</button></>:<p className="mt-2 text-sm text-slate-500">{t('insufficient')}</p>}</section>
  <section className="mt-6 rounded-[24px] border border-teal-100 bg-teal-50/70 p-4"><p className="text-xs font-black uppercase text-teal-700">{lang==='de'?'Diese Woche':'Эта неделя'}</p><div className="mt-2 flex items-end gap-3"><strong className="text-3xl font-black">{week.length}</strong><span className="pb-1 text-sm text-slate-600">{lang==='de'?'Versuche':'завершённых попыток'}</span></div>{weekMinutes>0&&<p className="mt-1 text-sm text-slate-600">{weekMinutes} {t('minutes')}</p>}</section>
  <section className="mt-6 rounded-[24px] border bg-white p-4 sm:p-5"><div className="flex items-start gap-3"><Trophy className="h-6 w-6 shrink-0 text-teal-700"/><div><p className="text-xs font-black uppercase text-slate-400">{t('mockExam')}</p><h2 className="mt-1 text-xl font-black">{r.mockLabel}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{!r.dataSufficient?(lang==='de'?'Erst mehr echte Ergebnisse in allen vier Bereichen sammeln.':'Сначала выполните больше заданий во всех четырёх модулях.'):'Пробный экзамен доступен в любое время. Рекомендация учитывает результаты по всем четырём навыкам.'}</p></div></div><button type="button" onClick={onOpenMockExam} className="mt-4 min-h-11 w-full rounded-xl bg-slate-950 px-4 font-black text-white">{lang==='de'?'Probeprüfung öffnen':'Открыть пробный экзамен'}</button></section>
 </div>
}
